//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:54:21 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.CheckResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChckRspnV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChckRspnV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChckRspnInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.992.001.01}ChckRspnInf1"/>
 *         &lt;element name="LdFctrInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.992.001.01}LdFctrInf1" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChckRspnV01", propOrder = {
    "chckRspnInf",
    "ldFctrInf"
})
public class ChckRspnV01 {

    @XmlElement(name = "ChckRspnInf", required = true)
    protected ChckRspnInf1 chckRspnInf;
    @XmlElement(name = "LdFctrInf", required = true)
    protected List<LdFctrInf1> ldFctrInf;

    /**
     * Gets the value of the chckRspnInf property.
     * 
     * @return
     *     possible object is
     *     {@link ChckRspnInf1 }
     *     
     */
    public ChckRspnInf1 getChckRspnInf() {
        return chckRspnInf;
    }

    /**
     * Sets the value of the chckRspnInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChckRspnInf1 }
     *     
     */
    public void setChckRspnInf(ChckRspnInf1 value) {
        this.chckRspnInf = value;
    }

    /**
     * Gets the value of the ldFctrInf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ldFctrInf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLdFctrInf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LdFctrInf1 }
     * 
     * 
     */
    public List<LdFctrInf1> getLdFctrInf() {
        if (ldFctrInf == null) {
            ldFctrInf = new ArrayList<LdFctrInf1>();
        }
        return this.ldFctrInf;
    }

}
