//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:52 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.AuthorityChangeNotification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuthrtySnCd1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AuthrtySnCd1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AS00"/>
 *     &lt;enumeration value="AS01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AuthrtySnCd1")
@XmlEnum
public enum AuthrtySnCd1 {

    @XmlEnumValue("AS00")
    AS_00("AS00"),
    @XmlEnumValue("AS01")
    AS_01("AS01");
    private final String value;

    AuthrtySnCd1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AuthrtySnCd1 fromValue(String v) {
        for (AuthrtySnCd1 c: AuthrtySnCd1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
