//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:04 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.LoginResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LoginRspnInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginRspnInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoginOprTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}LoginOperationTypeCode1"/>
 *         &lt;element name="CurSysDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}ISODate"/>
 *         &lt;element name="CurSysSts" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}Max2Text"/>
 *         &lt;element name="PrcSts" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}Max4Text"/>
 *         &lt;element name="PrcCd" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}Max8Text" minOccurs="0"/>
 *         &lt;element name="RjctInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.806.001.02}Max105Text" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginRspnInf1", propOrder = {
    "loginOprTp",
    "curSysDt",
    "curSysSts",
    "prcSts",
    "prcCd",
    "rjctInf"
})
public class LoginRspnInf1 {

    @XmlElement(name = "LoginOprTp", required = true)
    protected LoginOperationTypeCode1 loginOprTp;
    @XmlElement(name = "CurSysDt", required = true)
    protected XMLGregorianCalendar curSysDt;
    @XmlElement(name = "CurSysSts", required = true)
    protected String curSysSts;
    @XmlElement(name = "PrcSts", required = true)
    protected String prcSts;
    @XmlElement(name = "PrcCd")
    protected String prcCd;
    @XmlElement(name = "RjctInf")
    protected String rjctInf;

    /**
     * Gets the value of the loginOprTp property.
     * 
     * @return
     *     possible object is
     *     {@link LoginOperationTypeCode1 }
     *     
     */
    public LoginOperationTypeCode1 getLoginOprTp() {
        return loginOprTp;
    }

    /**
     * Sets the value of the loginOprTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginOperationTypeCode1 }
     *     
     */
    public void setLoginOprTp(LoginOperationTypeCode1 value) {
        this.loginOprTp = value;
    }

    /**
     * Gets the value of the curSysDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurSysDt() {
        return curSysDt;
    }

    /**
     * Sets the value of the curSysDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurSysDt(XMLGregorianCalendar value) {
        this.curSysDt = value;
    }

    /**
     * Gets the value of the curSysSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurSysSts() {
        return curSysSts;
    }

    /**
     * Sets the value of the curSysSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurSysSts(String value) {
        this.curSysSts = value;
    }

    /**
     * Gets the value of the prcSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrcSts() {
        return prcSts;
    }

    /**
     * Sets the value of the prcSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrcSts(String value) {
        this.prcSts = value;
    }

    /**
     * Gets the value of the prcCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrcCd() {
        return prcCd;
    }

    /**
     * Sets the value of the prcCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrcCd(String value) {
        this.prcCd = value;
    }

    /**
     * Gets the value of the rjctInf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRjctInf() {
        return rjctInf;
    }

    /**
     * Sets the value of the rjctInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRjctInf(String value) {
        this.rjctInf = value;
    }

}
