//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 04:33:44 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:cnaps:std:beps:2010:tech:xsd:beps.387.001.01", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zcbspay.platform.cnaps.beps.bean.RealTimePaymentByAgencyResponse;
