package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsStoppingnotiyLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_STOPPINGNOTIY_LOG")
public class CnapsStoppingnotiyLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 5559110553751464080L;
	private long tid;
	private String msgid;
	private String newstatus;
	private String effectivedate;
	private String estimatedstartservice;
	private String nodecode;
	private String partyidentification;
	private String notes;
	private String remarks;

	public CnapsStoppingnotiyLogDO() {
	}

	public CnapsStoppingnotiyLogDO(long tid) {
		this.tid = tid;
	}

	public CnapsStoppingnotiyLogDO(long tid, String msgid, String newstatus,
			String effectivedate, String estimatedstartservice,
			String nodecode, String partyidentification, String notes,
			String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.newstatus = newstatus;
		this.effectivedate = effectivedate;
		this.estimatedstartservice = estimatedstartservice;
		this.nodecode = nodecode;
		this.partyidentification = partyidentification;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "NEWSTATUS", length = 4)
	public String getNewstatus() {
		return this.newstatus;
	}

	public void setNewstatus(String newstatus) {
		this.newstatus = newstatus;
	}

	@Column(name = "EFFECTIVEDATE", length = 14)
	public String getEffectivedate() {
		return this.effectivedate;
	}

	public void setEffectivedate(String effectivedate) {
		this.effectivedate = effectivedate;
	}

	@Column(name = "ESTIMATEDSTARTSERVICE", length = 14)
	public String getEstimatedstartservice() {
		return this.estimatedstartservice;
	}

	public void setEstimatedstartservice(String estimatedstartservice) {
		this.estimatedstartservice = estimatedstartservice;
	}

	@Column(name = "NODECODE", length = 4)
	public String getNodecode() {
		return this.nodecode;
	}

	public void setNodecode(String nodecode) {
		this.nodecode = nodecode;
	}

	@Column(name = "PARTYIDENTIFICATION", length = 14)
	public String getPartyidentification() {
		return this.partyidentification;
	}

	public void setPartyidentification(String partyidentification) {
		this.partyidentification = partyidentification;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
