package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsQueryLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_QUERY_LOG")
public class CnapsQueryLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 3026160367811327841L;
	private long tid;
	private String msgid;
	private String instructionreference;
	private String referenceinstruction;
	private String referencemessagecode;
	private String brInstructingparty;
	private String brOrgnlmsgid;
	private String brNpcDate;
	private String brNpcProprietarystatus;
	private String brNpcReason;
	private String brNpcPurpose;
	private Short brNpcProprietarycode;
	private String brNpcFromdatetime;
	private String brNpcTodatetime;
	private String paymentinstructionstatus;
	private String brNpcInterbankvaluedate;
	private String brNpcRelatedreference;
	private String orProprietary;
	private String orDescription;
	private String notes;
	private String remarks;

	public CnapsQueryLogDO() {
	}

	public CnapsQueryLogDO(long tid) {
		this.tid = tid;
	}

	public CnapsQueryLogDO(long tid, String msgid, String instructionreference,
			String referenceinstruction, String referencemessagecode,
			String brInstructingparty, String brOrgnlmsgid, String brNpcDate,
			String brNpcProprietarystatus, String brNpcReason,
			String brNpcPurpose, Short brNpcProprietarycode,
			String brNpcFromdatetime, String brNpcTodatetime,
			String paymentinstructionstatus, String brNpcInterbankvaluedate,
			String brNpcRelatedreference, String orProprietary,
			String orDescription, String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.instructionreference = instructionreference;
		this.referenceinstruction = referenceinstruction;
		this.referencemessagecode = referencemessagecode;
		this.brInstructingparty = brInstructingparty;
		this.brOrgnlmsgid = brOrgnlmsgid;
		this.brNpcDate = brNpcDate;
		this.brNpcProprietarystatus = brNpcProprietarystatus;
		this.brNpcReason = brNpcReason;
		this.brNpcPurpose = brNpcPurpose;
		this.brNpcProprietarycode = brNpcProprietarycode;
		this.brNpcFromdatetime = brNpcFromdatetime;
		this.brNpcTodatetime = brNpcTodatetime;
		this.paymentinstructionstatus = paymentinstructionstatus;
		this.brNpcInterbankvaluedate = brNpcInterbankvaluedate;
		this.brNpcRelatedreference = brNpcRelatedreference;
		this.orProprietary = orProprietary;
		this.orDescription = orDescription;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "INSTRUCTIONREFERENCE", length = 35)
	public String getInstructionreference() {
		return this.instructionreference;
	}

	public void setInstructionreference(String instructionreference) {
		this.instructionreference = instructionreference;
	}

	@Column(name = "REFERENCEINSTRUCTION", length = 70)
	public String getReferenceinstruction() {
		return this.referenceinstruction;
	}

	public void setReferenceinstruction(String referenceinstruction) {
		this.referenceinstruction = referenceinstruction;
	}

	@Column(name = "REFERENCEMESSAGECODE", length = 70)
	public String getReferencemessagecode() {
		return this.referencemessagecode;
	}

	public void setReferencemessagecode(String referencemessagecode) {
		this.referencemessagecode = referencemessagecode;
	}

	@Column(name = "BR_INSTRUCTINGPARTY", length = 14)
	public String getBrInstructingparty() {
		return this.brInstructingparty;
	}

	public void setBrInstructingparty(String brInstructingparty) {
		this.brInstructingparty = brInstructingparty;
	}

	@Column(name = "BR_ORGNLMSGID", length = 35)
	public String getBrOrgnlmsgid() {
		return this.brOrgnlmsgid;
	}

	public void setBrOrgnlmsgid(String brOrgnlmsgid) {
		this.brOrgnlmsgid = brOrgnlmsgid;
	}

	@Column(name = "BR_NPC_DATE", length = 14)
	public String getBrNpcDate() {
		return this.brNpcDate;
	}

	public void setBrNpcDate(String brNpcDate) {
		this.brNpcDate = brNpcDate;
	}

	@Column(name = "BR_NPC_PROPRIETARYSTATUS", length = 4)
	public String getBrNpcProprietarystatus() {
		return this.brNpcProprietarystatus;
	}

	public void setBrNpcProprietarystatus(String brNpcProprietarystatus) {
		this.brNpcProprietarystatus = brNpcProprietarystatus;
	}

	@Column(name = "BR_NPC_REASON", length = 210)
	public String getBrNpcReason() {
		return this.brNpcReason;
	}

	public void setBrNpcReason(String brNpcReason) {
		this.brNpcReason = brNpcReason;
	}

	@Column(name = "BR_NPC_PURPOSE", length = 4)
	public String getBrNpcPurpose() {
		return this.brNpcPurpose;
	}

	public void setBrNpcPurpose(String brNpcPurpose) {
		this.brNpcPurpose = brNpcPurpose;
	}

	@Column(name = "BR_NPC_PROPRIETARYCODE", precision = 4, scale = 0)
	public Short getBrNpcProprietarycode() {
		return this.brNpcProprietarycode;
	}

	public void setBrNpcProprietarycode(Short brNpcProprietarycode) {
		this.brNpcProprietarycode = brNpcProprietarycode;
	}

	@Column(name = "BR_NPC_FROMDATETIME", length = 14)
	public String getBrNpcFromdatetime() {
		return this.brNpcFromdatetime;
	}

	public void setBrNpcFromdatetime(String brNpcFromdatetime) {
		this.brNpcFromdatetime = brNpcFromdatetime;
	}

	@Column(name = "BR_NPC_TODATETIME", length = 14)
	public String getBrNpcTodatetime() {
		return this.brNpcTodatetime;
	}

	public void setBrNpcTodatetime(String brNpcTodatetime) {
		this.brNpcTodatetime = brNpcTodatetime;
	}

	@Column(name = "PAYMENTINSTRUCTIONSTATUS", length = 2)
	public String getPaymentinstructionstatus() {
		return this.paymentinstructionstatus;
	}

	public void setPaymentinstructionstatus(String paymentinstructionstatus) {
		this.paymentinstructionstatus = paymentinstructionstatus;
	}

	@Column(name = "BR_NPC_INTERBANKVALUEDATE", length = 14)
	public String getBrNpcInterbankvaluedate() {
		return this.brNpcInterbankvaluedate;
	}

	public void setBrNpcInterbankvaluedate(String brNpcInterbankvaluedate) {
		this.brNpcInterbankvaluedate = brNpcInterbankvaluedate;
	}

	@Column(name = "BR_NPC_RELATEDREFERENCE", length = 8)
	public String getBrNpcRelatedreference() {
		return this.brNpcRelatedreference;
	}

	public void setBrNpcRelatedreference(String brNpcRelatedreference) {
		this.brNpcRelatedreference = brNpcRelatedreference;
	}

	@Column(name = "OR_PROPRIETARY", length = 4)
	public String getOrProprietary() {
		return this.orProprietary;
	}

	public void setOrProprietary(String orProprietary) {
		this.orProprietary = orProprietary;
	}

	@Column(name = "OR_DESCRIPTION", length = 8)
	public String getOrDescription() {
		return this.orDescription;
	}

	public void setOrDescription(String orDescription) {
		this.orDescription = orDescription;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
