package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsSystemStatusLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_SYSTEM_STATUS_LOG")
public class CnapsSystemStatusLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2615211932939622074L;
	private long tid;
	private String msgid;
	private String originalsystemdate;
	private String originalsystemstatus;
	private String currentsystemdate;
	private String currentsystemstatus;
	private String holidayflag;
	private String nextsystemdate;
	private String bankchangenumber;
	private String basedatachangenumber;
	private String cischangenumber;
	private String parameterchangenumber;
	private String notes;
	private String remarks;

	public CnapsSystemStatusLogDO() {
	}

	public CnapsSystemStatusLogDO(long tid) {
		this.tid = tid;
	}

	public CnapsSystemStatusLogDO(long tid, String msgid,
			String originalsystemdate, String originalsystemstatus,
			String currentsystemdate, String currentsystemstatus,
			String holidayflag, String nextsystemdate, String bankchangenumber,
			String basedatachangenumber, String cischangenumber,
			String parameterchangenumber, String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.originalsystemdate = originalsystemdate;
		this.originalsystemstatus = originalsystemstatus;
		this.currentsystemdate = currentsystemdate;
		this.currentsystemstatus = currentsystemstatus;
		this.holidayflag = holidayflag;
		this.nextsystemdate = nextsystemdate;
		this.bankchangenumber = bankchangenumber;
		this.basedatachangenumber = basedatachangenumber;
		this.cischangenumber = cischangenumber;
		this.parameterchangenumber = parameterchangenumber;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "ORIGINALSYSTEMDATE", length = 14)
	public String getOriginalsystemdate() {
		return this.originalsystemdate;
	}

	public void setOriginalsystemdate(String originalsystemdate) {
		this.originalsystemdate = originalsystemdate;
	}

	@Column(name = "ORIGINALSYSTEMSTATUS", length = 2)
	public String getOriginalsystemstatus() {
		return this.originalsystemstatus;
	}

	public void setOriginalsystemstatus(String originalsystemstatus) {
		this.originalsystemstatus = originalsystemstatus;
	}

	@Column(name = "CURRENTSYSTEMDATE", length = 14)
	public String getCurrentsystemdate() {
		return this.currentsystemdate;
	}

	public void setCurrentsystemdate(String currentsystemdate) {
		this.currentsystemdate = currentsystemdate;
	}

	@Column(name = "CURRENTSYSTEMSTATUS", length = 2)
	public String getCurrentsystemstatus() {
		return this.currentsystemstatus;
	}

	public void setCurrentsystemstatus(String currentsystemstatus) {
		this.currentsystemstatus = currentsystemstatus;
	}

	@Column(name = "HOLIDAYFLAG", length = 4)
	public String getHolidayflag() {
		return this.holidayflag;
	}

	public void setHolidayflag(String holidayflag) {
		this.holidayflag = holidayflag;
	}

	@Column(name = "NEXTSYSTEMDATE", length = 14)
	public String getNextsystemdate() {
		return this.nextsystemdate;
	}

	public void setNextsystemdate(String nextsystemdate) {
		this.nextsystemdate = nextsystemdate;
	}

	@Column(name = "BANKCHANGENUMBER", length = 8)
	public String getBankchangenumber() {
		return this.bankchangenumber;
	}

	public void setBankchangenumber(String bankchangenumber) {
		this.bankchangenumber = bankchangenumber;
	}

	@Column(name = "BASEDATACHANGENUMBER", length = 8)
	public String getBasedatachangenumber() {
		return this.basedatachangenumber;
	}

	public void setBasedatachangenumber(String basedatachangenumber) {
		this.basedatachangenumber = basedatachangenumber;
	}

	@Column(name = "CISCHANGENUMBER", length = 8)
	public String getCischangenumber() {
		return this.cischangenumber;
	}

	public void setCischangenumber(String cischangenumber) {
		this.cischangenumber = cischangenumber;
	}

	@Column(name = "PARAMETERCHANGENUMBER", length = 8)
	public String getParameterchangenumber() {
		return this.parameterchangenumber;
	}

	public void setParameterchangenumber(String parameterchangenumber) {
		this.parameterchangenumber = parameterchangenumber;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
