package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsTransactionAuthority generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_TRANSACTION_AUTHORITY")
public class CnapsTransactionAuthorityDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2879342528493659105L;
	private long tid;
	private String initiateparticipant;
	private String receiveparticipant;
	private String messagetype;
	private String transactiontypecode;
	private String authoritysigncode;
	private String authorityweight;
	private String notes;
	private String remarks;

	public CnapsTransactionAuthorityDO() {
	}

	public CnapsTransactionAuthorityDO(long tid) {
		this.tid = tid;
	}

	public CnapsTransactionAuthorityDO(long tid, String initiateparticipant,
			String receiveparticipant, String messagetype,
			String transactiontypecode, String authoritysigncode,
			String authorityweight, String notes, String remarks) {
		this.tid = tid;
		this.initiateparticipant = initiateparticipant;
		this.receiveparticipant = receiveparticipant;
		this.messagetype = messagetype;
		this.transactiontypecode = transactiontypecode;
		this.authoritysigncode = authoritysigncode;
		this.authorityweight = authorityweight;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "INITIATEPARTICIPANT", length = 14)
	public String getInitiateparticipant() {
		return this.initiateparticipant;
	}

	public void setInitiateparticipant(String initiateparticipant) {
		this.initiateparticipant = initiateparticipant;
	}

	@Column(name = "RECEIVEPARTICIPANT", length = 14)
	public String getReceiveparticipant() {
		return this.receiveparticipant;
	}

	public void setReceiveparticipant(String receiveparticipant) {
		this.receiveparticipant = receiveparticipant;
	}

	@Column(name = "MESSAGETYPE", length = 20)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "TRANSACTIONTYPECODE", length = 5)
	public String getTransactiontypecode() {
		return this.transactiontypecode;
	}

	public void setTransactiontypecode(String transactiontypecode) {
		this.transactiontypecode = transactiontypecode;
	}

	@Column(name = "AUTHORITYSIGNCODE", length = 4)
	public String getAuthoritysigncode() {
		return this.authoritysigncode;
	}

	public void setAuthoritysigncode(String authoritysigncode) {
		this.authoritysigncode = authoritysigncode;
	}

	@Column(name = "AUTHORITYWEIGHT", length = 2)
	public String getAuthorityweight() {
		return this.authorityweight;
	}

	public void setAuthorityweight(String authorityweight) {
		this.authorityweight = authorityweight;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
