package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsCustomerAccount generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_CUSTOMER_ACCOUNT")
public class CnapsCustomerAccountDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2634875215224224665L;
	private long tid;
	private String accountno;
	private String accountname;
	private String accountbank;
	private String accountstatus;
	private String notes;
	private String remarks;

	public CnapsCustomerAccountDO() {
	}

	public CnapsCustomerAccountDO(long tid) {
		this.tid = tid;
	}

	public CnapsCustomerAccountDO(long tid, String accountno,
			String accountname, String accountbank, String accountstatus,
			String notes, String remarks) {
		this.tid = tid;
		this.accountno = accountno;
		this.accountname = accountname;
		this.accountbank = accountbank;
		this.accountstatus = accountstatus;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "ACCOUNTNO", length = 32)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	@Column(name = "ACCOUNTNAME", length = 32)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	@Column(name = "ACCOUNTBANK", length = 14)
	public String getAccountbank() {
		return this.accountbank;
	}

	public void setAccountbank(String accountbank) {
		this.accountbank = accountbank;
	}

	@Column(name = "ACCOUNTSTATUS", length = 4)
	public String getAccountstatus() {
		return this.accountstatus;
	}

	public void setAccountstatus(String accountstatus) {
		this.accountstatus = accountstatus;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
