package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsDetailBillApply generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_DETAIL_BILL_APPLY")
public class CnapsDetailBillApplyDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 499335493246514673L;
	private long tid;
	private String msgid;
	private String checkdate;
	private String sendreceivetype;
	private String transactionnettingdate;
	private Integer transactionnettinground;
	private String messagetype;
	private String processstatus;
	private String comprocessstatus;
	private String comprocesscode;
	private String compartyidentification;
	private String compartyprocesscode;
	private String comrejectinformation;
	private String comprocessdate;
	private String comnettinground;
	private String comdate;
	private String notes;
	private String remarks;

	public CnapsDetailBillApplyDO() {
	}

	public CnapsDetailBillApplyDO(long tid) {
		this.tid = tid;
	}

	public CnapsDetailBillApplyDO(long tid, String msgid, String checkdate,
			String sendreceivetype, String transactionnettingdate,
			Integer transactionnettinground, String messagetype,
			String processstatus, String comprocessstatus,
			String comprocesscode, String compartyidentification,
			String compartyprocesscode, String comrejectinformation,
			String comprocessdate, String comnettinground, String comdate,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.checkdate = checkdate;
		this.sendreceivetype = sendreceivetype;
		this.transactionnettingdate = transactionnettingdate;
		this.transactionnettinground = transactionnettinground;
		this.messagetype = messagetype;
		this.processstatus = processstatus;
		this.comprocessstatus = comprocessstatus;
		this.comprocesscode = comprocesscode;
		this.compartyidentification = compartyidentification;
		this.compartyprocesscode = compartyprocesscode;
		this.comrejectinformation = comrejectinformation;
		this.comprocessdate = comprocessdate;
		this.comnettinground = comnettinground;
		this.comdate = comdate;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "CHECKDATE", length = 14)
	public String getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(String checkdate) {
		this.checkdate = checkdate;
	}

	@Column(name = "SENDRECEIVETYPE", length = 4)
	public String getSendreceivetype() {
		return this.sendreceivetype;
	}

	public void setSendreceivetype(String sendreceivetype) {
		this.sendreceivetype = sendreceivetype;
	}

	@Column(name = "TRANSACTIONNETTINGDATE", length = 14)
	public String getTransactionnettingdate() {
		return this.transactionnettingdate;
	}

	public void setTransactionnettingdate(String transactionnettingdate) {
		this.transactionnettingdate = transactionnettingdate;
	}

	@Column(name = "TRANSACTIONNETTINGROUND", precision = 8, scale = 0)
	public Integer getTransactionnettinground() {
		return this.transactionnettinground;
	}

	public void setTransactionnettinground(Integer transactionnettinground) {
		this.transactionnettinground = transactionnettinground;
	}

	@Column(name = "MESSAGETYPE", length = 35)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "PROCESSSTATUS", length = 4)
	public String getProcessstatus() {
		return this.processstatus;
	}

	public void setProcessstatus(String processstatus) {
		this.processstatus = processstatus;
	}

	@Column(name = "COMPROCESSSTATUS", length = 4)
	public String getComprocessstatus() {
		return this.comprocessstatus;
	}

	public void setComprocessstatus(String comprocessstatus) {
		this.comprocessstatus = comprocessstatus;
	}

	@Column(name = "COMPROCESSCODE", length = 8)
	public String getComprocesscode() {
		return this.comprocesscode;
	}

	public void setComprocesscode(String comprocesscode) {
		this.comprocesscode = comprocesscode;
	}

	@Column(name = "COMPARTYIDENTIFICATION", length = 14)
	public String getCompartyidentification() {
		return this.compartyidentification;
	}

	public void setCompartyidentification(String compartyidentification) {
		this.compartyidentification = compartyidentification;
	}

	@Column(name = "COMPARTYPROCESSCODE", length = 4)
	public String getCompartyprocesscode() {
		return this.compartyprocesscode;
	}

	public void setCompartyprocesscode(String compartyprocesscode) {
		this.compartyprocesscode = compartyprocesscode;
	}

	@Column(name = "COMREJECTINFORMATION", length = 210)
	public String getComrejectinformation() {
		return this.comrejectinformation;
	}

	public void setComrejectinformation(String comrejectinformation) {
		this.comrejectinformation = comrejectinformation;
	}

	@Column(name = "COMPROCESSDATE", length = 14)
	public String getComprocessdate() {
		return this.comprocessdate;
	}

	public void setComprocessdate(String comprocessdate) {
		this.comprocessdate = comprocessdate;
	}

	@Column(name = "COMNETTINGROUND", length = 2)
	public String getComnettinground() {
		return this.comnettinground;
	}

	public void setComnettinground(String comnettinground) {
		this.comnettinground = comnettinground;
	}

	@Column(name = "COMDATE", length = 14)
	public String getComdate() {
		return this.comdate;
	}

	public void setComdate(String comdate) {
		this.comdate = comdate;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
