package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsCollectBatchLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_COLLECT_BATCH_LOG")
public class CnapsCollectBatchLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -1303091511765659044L;
	private long tid;
	private String msgid;
	private String batchno;
	private String transmitdate;
	private String returnlimited;
	private String debtorbranchcode;
	private String debtoragentcode;
	private String creditoragentcode;
	private String creditorbranchcode;
	private String creditorname;
	private String creditoraccountno;
	private long totalamount;
	private String categorypurposecode;
	private int debtornumber;
	private Integer receivingtotalnumber;
	private Long receivingtotalamount;
	private Integer failtotalnumber;
	private Long failtotalamount;
	private String npcprocessstatus;
	private String npcprocesscode;
	private String npcrejectinformation;
	private String npcnettingdate;
	private Byte npcnettinground;
	private String npcsettlementdate;
	private String npcreceivetime;
	private String npctransmittime;
	private String rspstatus;
	private String rsprejectcode;
	private String rsprejectinformation;
	private String rspprocessparty;
	private String rspdate;
	private String comprocessstatus;
	private String comprocesscode;
	private String compartyidentification;
	private String compartyprocesscode;
	private String comrejectinformation;
	private String comprocessdate;
	private String comnettinground;
	private String comdate;
	private String notes;
	private String remarks;

	public CnapsCollectBatchLogDO() {
	}

	public CnapsCollectBatchLogDO(long tid, String msgid, String batchno,
			String transmitdate, String returnlimited, String debtorbranchcode,
			String debtoragentcode, String creditoragentcode,
			String creditorbranchcode, String creditorname,
			String creditoraccountno, long totalamount,
			String categorypurposecode, int debtornumber) {
		this.tid = tid;
		this.msgid = msgid;
		this.batchno = batchno;
		this.transmitdate = transmitdate;
		this.returnlimited = returnlimited;
		this.debtorbranchcode = debtorbranchcode;
		this.debtoragentcode = debtoragentcode;
		this.creditoragentcode = creditoragentcode;
		this.creditorbranchcode = creditorbranchcode;
		this.creditorname = creditorname;
		this.creditoraccountno = creditoraccountno;
		this.totalamount = totalamount;
		this.categorypurposecode = categorypurposecode;
		this.debtornumber = debtornumber;
	}

	public CnapsCollectBatchLogDO(long tid, String msgid, String batchno,
			String transmitdate, String returnlimited, String debtorbranchcode,
			String debtoragentcode, String creditoragentcode,
			String creditorbranchcode, String creditorname,
			String creditoraccountno, long totalamount,
			String categorypurposecode, int debtornumber,
			Integer receivingtotalnumber, Long receivingtotalamount,
			Integer failtotalnumber, Long failtotalamount,
			String npcprocessstatus, String npcprocesscode,
			String npcrejectinformation, String npcnettingdate,
			Byte npcnettinground, String npcsettlementdate,
			String npcreceivetime, String npctransmittime, String rspstatus,
			String rsprejectcode, String rsprejectinformation,
			String rspprocessparty, String rspdate, String comprocessstatus,
			String comprocesscode, String compartyidentification,
			String compartyprocesscode, String comrejectinformation,
			String comprocessdate, String comnettinground, String comdate,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.batchno = batchno;
		this.transmitdate = transmitdate;
		this.returnlimited = returnlimited;
		this.debtorbranchcode = debtorbranchcode;
		this.debtoragentcode = debtoragentcode;
		this.creditoragentcode = creditoragentcode;
		this.creditorbranchcode = creditorbranchcode;
		this.creditorname = creditorname;
		this.creditoraccountno = creditoraccountno;
		this.totalamount = totalamount;
		this.categorypurposecode = categorypurposecode;
		this.debtornumber = debtornumber;
		this.receivingtotalnumber = receivingtotalnumber;
		this.receivingtotalamount = receivingtotalamount;
		this.failtotalnumber = failtotalnumber;
		this.failtotalamount = failtotalamount;
		this.npcprocessstatus = npcprocessstatus;
		this.npcprocesscode = npcprocesscode;
		this.npcrejectinformation = npcrejectinformation;
		this.npcnettingdate = npcnettingdate;
		this.npcnettinground = npcnettinground;
		this.npcsettlementdate = npcsettlementdate;
		this.npcreceivetime = npcreceivetime;
		this.npctransmittime = npctransmittime;
		this.rspstatus = rspstatus;
		this.rsprejectcode = rsprejectcode;
		this.rsprejectinformation = rsprejectinformation;
		this.rspprocessparty = rspprocessparty;
		this.rspdate = rspdate;
		this.comprocessstatus = comprocessstatus;
		this.comprocesscode = comprocesscode;
		this.compartyidentification = compartyidentification;
		this.compartyprocesscode = compartyprocesscode;
		this.comrejectinformation = comrejectinformation;
		this.comprocessdate = comprocessdate;
		this.comnettinground = comnettinground;
		this.comdate = comdate;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", nullable = false, length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "BATCHNO", nullable = false, length = 8)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "TRANSMITDATE", nullable = false, length = 14)
	public String getTransmitdate() {
		return this.transmitdate;
	}

	public void setTransmitdate(String transmitdate) {
		this.transmitdate = transmitdate;
	}

	@Column(name = "RETURNLIMITED", nullable = false, length = 2)
	public String getReturnlimited() {
		return this.returnlimited;
	}

	public void setReturnlimited(String returnlimited) {
		this.returnlimited = returnlimited;
	}

	@Column(name = "DEBTORBRANCHCODE", nullable = false, length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "DEBTORAGENTCODE", nullable = false, length = 14)
	public String getDebtoragentcode() {
		return this.debtoragentcode;
	}

	public void setDebtoragentcode(String debtoragentcode) {
		this.debtoragentcode = debtoragentcode;
	}

	@Column(name = "CREDITORAGENTCODE", nullable = false, length = 14)
	public String getCreditoragentcode() {
		return this.creditoragentcode;
	}

	public void setCreditoragentcode(String creditoragentcode) {
		this.creditoragentcode = creditoragentcode;
	}

	@Column(name = "CREDITORBRANCHCODE", nullable = false, length = 14)
	public String getCreditorbranchcode() {
		return this.creditorbranchcode;
	}

	public void setCreditorbranchcode(String creditorbranchcode) {
		this.creditorbranchcode = creditorbranchcode;
	}

	@Column(name = "CREDITORNAME", nullable = false, length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "CREDITORACCOUNTNO", nullable = false, length = 32)
	public String getCreditoraccountno() {
		return this.creditoraccountno;
	}

	public void setCreditoraccountno(String creditoraccountno) {
		this.creditoraccountno = creditoraccountno;
	}

	@Column(name = "TOTALAMOUNT", nullable = false, precision = 12, scale = 0)
	public long getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(long totalamount) {
		this.totalamount = totalamount;
	}

	@Column(name = "CATEGORYPURPOSECODE", nullable = false, length = 4)
	public String getCategorypurposecode() {
		return this.categorypurposecode;
	}

	public void setCategorypurposecode(String categorypurposecode) {
		this.categorypurposecode = categorypurposecode;
	}

	@Column(name = "DEBTORNUMBER", nullable = false, precision = 8, scale = 0)
	public int getDebtornumber() {
		return this.debtornumber;
	}

	public void setDebtornumber(int debtornumber) {
		this.debtornumber = debtornumber;
	}

	@Column(name = "RECEIVINGTOTALNUMBER", precision = 8, scale = 0)
	public Integer getReceivingtotalnumber() {
		return this.receivingtotalnumber;
	}

	public void setReceivingtotalnumber(Integer receivingtotalnumber) {
		this.receivingtotalnumber = receivingtotalnumber;
	}

	@Column(name = "RECEIVINGTOTALAMOUNT", precision = 12, scale = 0)
	public Long getReceivingtotalamount() {
		return this.receivingtotalamount;
	}

	public void setReceivingtotalamount(Long receivingtotalamount) {
		this.receivingtotalamount = receivingtotalamount;
	}

	@Column(name = "FAILTOTALNUMBER", precision = 8, scale = 0)
	public Integer getFailtotalnumber() {
		return this.failtotalnumber;
	}

	public void setFailtotalnumber(Integer failtotalnumber) {
		this.failtotalnumber = failtotalnumber;
	}

	@Column(name = "FAILTOTALAMOUNT", precision = 12, scale = 0)
	public Long getFailtotalamount() {
		return this.failtotalamount;
	}

	public void setFailtotalamount(Long failtotalamount) {
		this.failtotalamount = failtotalamount;
	}

	@Column(name = "NPCPROCESSSTATUS", length = 4)
	public String getNpcprocessstatus() {
		return this.npcprocessstatus;
	}

	public void setNpcprocessstatus(String npcprocessstatus) {
		this.npcprocessstatus = npcprocessstatus;
	}

	@Column(name = "NPCPROCESSCODE", length = 8)
	public String getNpcprocesscode() {
		return this.npcprocesscode;
	}

	public void setNpcprocesscode(String npcprocesscode) {
		this.npcprocesscode = npcprocesscode;
	}

	@Column(name = "NPCREJECTINFORMATION", length = 210)
	public String getNpcrejectinformation() {
		return this.npcrejectinformation;
	}

	public void setNpcrejectinformation(String npcrejectinformation) {
		this.npcrejectinformation = npcrejectinformation;
	}

	@Column(name = "NPCNETTINGDATE", length = 14)
	public String getNpcnettingdate() {
		return this.npcnettingdate;
	}

	public void setNpcnettingdate(String npcnettingdate) {
		this.npcnettingdate = npcnettingdate;
	}

	@Column(name = "NPCNETTINGROUND", precision = 2, scale = 0)
	public Byte getNpcnettinground() {
		return this.npcnettinground;
	}

	public void setNpcnettinground(Byte npcnettinground) {
		this.npcnettinground = npcnettinground;
	}

	@Column(name = "NPCSETTLEMENTDATE", length = 14)
	public String getNpcsettlementdate() {
		return this.npcsettlementdate;
	}

	public void setNpcsettlementdate(String npcsettlementdate) {
		this.npcsettlementdate = npcsettlementdate;
	}

	@Column(name = "NPCRECEIVETIME", length = 14)
	public String getNpcreceivetime() {
		return this.npcreceivetime;
	}

	public void setNpcreceivetime(String npcreceivetime) {
		this.npcreceivetime = npcreceivetime;
	}

	@Column(name = "NPCTRANSMITTIME", length = 14)
	public String getNpctransmittime() {
		return this.npctransmittime;
	}

	public void setNpctransmittime(String npctransmittime) {
		this.npctransmittime = npctransmittime;
	}

	@Column(name = "RSPSTATUS", length = 4)
	public String getRspstatus() {
		return this.rspstatus;
	}

	public void setRspstatus(String rspstatus) {
		this.rspstatus = rspstatus;
	}

	@Column(name = "RSPREJECTCODE", length = 4)
	public String getRsprejectcode() {
		return this.rsprejectcode;
	}

	public void setRsprejectcode(String rsprejectcode) {
		this.rsprejectcode = rsprejectcode;
	}

	@Column(name = "RSPREJECTINFORMATION", length = 210)
	public String getRsprejectinformation() {
		return this.rsprejectinformation;
	}

	public void setRsprejectinformation(String rsprejectinformation) {
		this.rsprejectinformation = rsprejectinformation;
	}

	@Column(name = "RSPPROCESSPARTY", length = 14)
	public String getRspprocessparty() {
		return this.rspprocessparty;
	}

	public void setRspprocessparty(String rspprocessparty) {
		this.rspprocessparty = rspprocessparty;
	}

	@Column(name = "RSPDATE", length = 14)
	public String getRspdate() {
		return this.rspdate;
	}

	public void setRspdate(String rspdate) {
		this.rspdate = rspdate;
	}

	@Column(name = "COMPROCESSSTATUS", length = 4)
	public String getComprocessstatus() {
		return this.comprocessstatus;
	}

	public void setComprocessstatus(String comprocessstatus) {
		this.comprocessstatus = comprocessstatus;
	}

	@Column(name = "COMPROCESSCODE", length = 8)
	public String getComprocesscode() {
		return this.comprocesscode;
	}

	public void setComprocesscode(String comprocesscode) {
		this.comprocesscode = comprocesscode;
	}

	@Column(name = "COMPARTYIDENTIFICATION", length = 14)
	public String getCompartyidentification() {
		return this.compartyidentification;
	}

	public void setCompartyidentification(String compartyidentification) {
		this.compartyidentification = compartyidentification;
	}

	@Column(name = "COMPARTYPROCESSCODE", length = 4)
	public String getCompartyprocesscode() {
		return this.compartyprocesscode;
	}

	public void setCompartyprocesscode(String compartyprocesscode) {
		this.compartyprocesscode = compartyprocesscode;
	}

	@Column(name = "COMREJECTINFORMATION", length = 210)
	public String getComrejectinformation() {
		return this.comrejectinformation;
	}

	public void setComrejectinformation(String comrejectinformation) {
		this.comrejectinformation = comrejectinformation;
	}

	@Column(name = "COMPROCESSDATE", length = 14)
	public String getComprocessdate() {
		return this.comprocessdate;
	}

	public void setComprocessdate(String comprocessdate) {
		this.comprocessdate = comprocessdate;
	}

	@Column(name = "COMNETTINGROUND", length = 2)
	public String getComnettinground() {
		return this.comnettinground;
	}

	public void setComnettinground(String comnettinground) {
		this.comnettinground = comnettinground;
	}

	@Column(name = "COMDATE", length = 14)
	public String getComdate() {
		return this.comdate;
	}

	public void setComdate(String comdate) {
		this.comdate = comdate;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
