package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsDetailBill generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_DETAIL_BILL")
public class CnapsDetailBillDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 5800227882677153335L;
	private long tid;
	private String msgid;
	private String checkdate;
	private String npcProcessstatus;
	private String npcProcesscode;
	private String sendreceivetype;
	private String transactionnettingdate;
	private Integer transactionnettinground;
	private String messagetype;
	private String processstatus;
	private String orgnlmsgid;
	private String orgnlinstgpty;
	private String originalmessagetype;
	private Integer totalcount;
	private Long controlsum;
	private String notes;
	private String remarks;

	public CnapsDetailBillDO() {
	}

	public CnapsDetailBillDO(long tid) {
		this.tid = tid;
	}

	public CnapsDetailBillDO(long tid, String msgid, String checkdate,
			String npcProcessstatus, String npcProcesscode,
			String sendreceivetype, String transactionnettingdate,
			Integer transactionnettinground, String messagetype,
			String processstatus, String orgnlmsgid, String orgnlinstgpty,
			String originalmessagetype, Integer totalcount, Long controlsum,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.checkdate = checkdate;
		this.npcProcessstatus = npcProcessstatus;
		this.npcProcesscode = npcProcesscode;
		this.sendreceivetype = sendreceivetype;
		this.transactionnettingdate = transactionnettingdate;
		this.transactionnettinground = transactionnettinground;
		this.messagetype = messagetype;
		this.processstatus = processstatus;
		this.orgnlmsgid = orgnlmsgid;
		this.orgnlinstgpty = orgnlinstgpty;
		this.originalmessagetype = originalmessagetype;
		this.totalcount = totalcount;
		this.controlsum = controlsum;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "CHECKDATE", length = 14)
	public String getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(String checkdate) {
		this.checkdate = checkdate;
	}

	@Column(name = "NPC_PROCESSSTATUS", length = 4)
	public String getNpcProcessstatus() {
		return this.npcProcessstatus;
	}

	public void setNpcProcessstatus(String npcProcessstatus) {
		this.npcProcessstatus = npcProcessstatus;
	}

	@Column(name = "NPC_PROCESSCODE", length = 8)
	public String getNpcProcesscode() {
		return this.npcProcesscode;
	}

	public void setNpcProcesscode(String npcProcesscode) {
		this.npcProcesscode = npcProcesscode;
	}

	@Column(name = "SENDRECEIVETYPE", length = 4)
	public String getSendreceivetype() {
		return this.sendreceivetype;
	}

	public void setSendreceivetype(String sendreceivetype) {
		this.sendreceivetype = sendreceivetype;
	}

	@Column(name = "TRANSACTIONNETTINGDATE", length = 14)
	public String getTransactionnettingdate() {
		return this.transactionnettingdate;
	}

	public void setTransactionnettingdate(String transactionnettingdate) {
		this.transactionnettingdate = transactionnettingdate;
	}

	@Column(name = "TRANSACTIONNETTINGROUND", precision = 8, scale = 0)
	public Integer getTransactionnettinground() {
		return this.transactionnettinground;
	}

	public void setTransactionnettinground(Integer transactionnettinground) {
		this.transactionnettinground = transactionnettinground;
	}

	@Column(name = "MESSAGETYPE", length = 35)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "PROCESSSTATUS", length = 4)
	public String getProcessstatus() {
		return this.processstatus;
	}

	public void setProcessstatus(String processstatus) {
		this.processstatus = processstatus;
	}

	@Column(name = "ORGNLMSGID", length = 35)
	public String getOrgnlmsgid() {
		return this.orgnlmsgid;
	}

	public void setOrgnlmsgid(String orgnlmsgid) {
		this.orgnlmsgid = orgnlmsgid;
	}

	@Column(name = "ORGNLINSTGPTY", length = 14)
	public String getOrgnlinstgpty() {
		return this.orgnlinstgpty;
	}

	public void setOrgnlinstgpty(String orgnlinstgpty) {
		this.orgnlinstgpty = orgnlinstgpty;
	}

	@Column(name = "ORIGINALMESSAGETYPE", length = 35)
	public String getOriginalmessagetype() {
		return this.originalmessagetype;
	}

	public void setOriginalmessagetype(String originalmessagetype) {
		this.originalmessagetype = originalmessagetype;
	}

	@Column(name = "TOTALCOUNT", precision = 8, scale = 0)
	public Integer getTotalcount() {
		return this.totalcount;
	}

	public void setTotalcount(Integer totalcount) {
		this.totalcount = totalcount;
	}

	@Column(name = "CONTROLSUM", precision = 12, scale = 0)
	public Long getControlsum() {
		return this.controlsum;
	}

	public void setControlsum(Long controlsum) {
		this.controlsum = controlsum;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
