package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsCommConfirmation generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_COMM_CONFIRMATION")
public class CnapsCommConfirmationDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -766140404117735498L;
	private long tid;
	private String msgid;
	private String origsender;
	private String origsenddate;
	private String mesgtype;
	private String messageidentification;
	private String msgreferenceidentification;
	private String messageprocesscode;
	private String notes;
	private String remarks;

	public CnapsCommConfirmationDO() {
	}

	public CnapsCommConfirmationDO(long tid) {
		this.tid = tid;
	}

	public CnapsCommConfirmationDO(long tid, String msgid, String origsender,
			String origsenddate, String mesgtype, String messageidentification,
			String msgreferenceidentification, String messageprocesscode,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.origsender = origsender;
		this.origsenddate = origsenddate;
		this.mesgtype = mesgtype;
		this.messageidentification = messageidentification;
		this.msgreferenceidentification = msgreferenceidentification;
		this.messageprocesscode = messageprocesscode;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "ORIGSENDER", length = 14)
	public String getOrigsender() {
		return this.origsender;
	}

	public void setOrigsender(String origsender) {
		this.origsender = origsender;
	}

	@Column(name = "ORIGSENDDATE", length = 8)
	public String getOrigsenddate() {
		return this.origsenddate;
	}

	public void setOrigsenddate(String origsenddate) {
		this.origsenddate = origsenddate;
	}

	@Column(name = "MESGTYPE", length = 20)
	public String getMesgtype() {
		return this.mesgtype;
	}

	public void setMesgtype(String mesgtype) {
		this.mesgtype = mesgtype;
	}

	@Column(name = "MESSAGEIDENTIFICATION", length = 20)
	public String getMessageidentification() {
		return this.messageidentification;
	}

	public void setMessageidentification(String messageidentification) {
		this.messageidentification = messageidentification;
	}

	@Column(name = "MSGREFERENCEIDENTIFICATION", length = 20)
	public String getMsgreferenceidentification() {
		return this.msgreferenceidentification;
	}

	public void setMsgreferenceidentification(String msgreferenceidentification) {
		this.msgreferenceidentification = msgreferenceidentification;
	}

	@Column(name = "MESSAGEPROCESSCODE", length = 8)
	public String getMessageprocesscode() {
		return this.messageprocesscode;
	}

	public void setMessageprocesscode(String messageprocesscode) {
		this.messageprocesscode = messageprocesscode;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
