package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsContractDetaLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_CONTRACT_DETA_LOG")
public class CnapsContractDetaLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2341802685584058304L;
	private long tid;
	private String msgid;
	private String changetypecode;
	private String agreementnumber;
	private String debtorname;
	private String debtoraccountno;
	private String debtorissuercode;
	private String debtoragentcode;
	private String debtorbranchcode;
	private String creditorname;
	private String rspstatus;
	private String rsprejectcode;
	private String rspprocessparty;
	private String rsprejectinformation;
	private String rspdate;
	private String accountstatus;
	private String notes;
	private String remarks;

	public CnapsContractDetaLogDO() {
	}

	public CnapsContractDetaLogDO(long tid, String msgid, String changetypecode,
			String agreementnumber, String debtorname, String debtoraccountno,
			String debtorissuercode, String debtoragentcode,
			String debtorbranchcode, String creditorname) {
		this.tid = tid;
		this.msgid = msgid;
		this.changetypecode = changetypecode;
		this.agreementnumber = agreementnumber;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtorissuercode = debtorissuercode;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditorname = creditorname;
	}

	public CnapsContractDetaLogDO(long tid, String msgid, String changetypecode,
			String agreementnumber, String debtorname, String debtoraccountno,
			String debtorissuercode, String debtoragentcode,
			String debtorbranchcode, String creditorname, String rspstatus,
			String rsprejectcode, String rspprocessparty,
			String rsprejectinformation, String rspdate, String accountstatus,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.changetypecode = changetypecode;
		this.agreementnumber = agreementnumber;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtorissuercode = debtorissuercode;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditorname = creditorname;
		this.rspstatus = rspstatus;
		this.rsprejectcode = rsprejectcode;
		this.rspprocessparty = rspprocessparty;
		this.rsprejectinformation = rsprejectinformation;
		this.rspdate = rspdate;
		this.accountstatus = accountstatus;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", nullable = false, length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "CHANGETYPECODE", nullable = false, length = 4)
	public String getChangetypecode() {
		return this.changetypecode;
	}

	public void setChangetypecode(String changetypecode) {
		this.changetypecode = changetypecode;
	}

	@Column(name = "AGREEMENTNUMBER", nullable = false, length = 60)
	public String getAgreementnumber() {
		return this.agreementnumber;
	}

	public void setAgreementnumber(String agreementnumber) {
		this.agreementnumber = agreementnumber;
	}

	@Column(name = "DEBTORNAME", nullable = false, length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORACCOUNTNO", nullable = false, length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "DEBTORISSUERCODE", nullable = false, length = 14)
	public String getDebtorissuercode() {
		return this.debtorissuercode;
	}

	public void setDebtorissuercode(String debtorissuercode) {
		this.debtorissuercode = debtorissuercode;
	}

	@Column(name = "DEBTORAGENTCODE", nullable = false, length = 14)
	public String getDebtoragentcode() {
		return this.debtoragentcode;
	}

	public void setDebtoragentcode(String debtoragentcode) {
		this.debtoragentcode = debtoragentcode;
	}

	@Column(name = "DEBTORBRANCHCODE", nullable = false, length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "CREDITORNAME", nullable = false, length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "RSPSTATUS", length = 4)
	public String getRspstatus() {
		return this.rspstatus;
	}

	public void setRspstatus(String rspstatus) {
		this.rspstatus = rspstatus;
	}

	@Column(name = "RSPREJECTCODE", length = 4)
	public String getRsprejectcode() {
		return this.rsprejectcode;
	}

	public void setRsprejectcode(String rsprejectcode) {
		this.rsprejectcode = rsprejectcode;
	}

	@Column(name = "RSPPROCESSPARTY", length = 14)
	public String getRspprocessparty() {
		return this.rspprocessparty;
	}

	public void setRspprocessparty(String rspprocessparty) {
		this.rspprocessparty = rspprocessparty;
	}

	@Column(name = "RSPREJECTINFORMATION", length = 210)
	public String getRsprejectinformation() {
		return this.rsprejectinformation;
	}

	public void setRsprejectinformation(String rsprejectinformation) {
		this.rsprejectinformation = rsprejectinformation;
	}

	@Column(name = "RSPDATE", length = 14)
	public String getRspdate() {
		return this.rspdate;
	}

	public void setRspdate(String rspdate) {
		this.rspdate = rspdate;
	}

	@Column(name = "ACCOUNTSTATUS", length = 4)
	public String getAccountstatus() {
		return this.accountstatus;
	}

	public void setAccountstatus(String accountstatus) {
		this.accountstatus = accountstatus;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
