package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsBusiType generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_BUSI_TYPE")
public class CnapsBusiTypeDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2804036991990460586L;
	private long tid;
	private String transactiontypecode;
	private String transactiontypename;
	private String categorypurposecode;
	private String categorypurposename;
	private String notes;
	private String remarks;

	public CnapsBusiTypeDO() {
	}

	public CnapsBusiTypeDO(long tid) {
		this.tid = tid;
	}

	public CnapsBusiTypeDO(long tid, String transactiontypecode,
			String transactiontypename, String categorypurposecode,
			String categorypurposename, String notes, String remarks) {
		this.tid = tid;
		this.transactiontypecode = transactiontypecode;
		this.transactiontypename = transactiontypename;
		this.categorypurposecode = categorypurposecode;
		this.categorypurposename = categorypurposename;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "TRANSACTIONTYPECODE", length = 4)
	public String getTransactiontypecode() {
		return this.transactiontypecode;
	}

	public void setTransactiontypecode(String transactiontypecode) {
		this.transactiontypecode = transactiontypecode;
	}

	@Column(name = "TRANSACTIONTYPENAME", length = 60)
	public String getTransactiontypename() {
		return this.transactiontypename;
	}

	public void setTransactiontypename(String transactiontypename) {
		this.transactiontypename = transactiontypename;
	}

	@Column(name = "CATEGORYPURPOSECODE", length = 5)
	public String getCategorypurposecode() {
		return this.categorypurposecode;
	}

	public void setCategorypurposecode(String categorypurposecode) {
		this.categorypurposecode = categorypurposecode;
	}

	@Column(name = "CATEGORYPURPOSENAME", length = 120)
	public String getCategorypurposename() {
		return this.categorypurposename;
	}

	public void setCategorypurposename(String categorypurposename) {
		this.categorypurposename = categorypurposename;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
