package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsAmountLimit generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_AMOUNT_LIMIT")
public class CnapsAmountLimitDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -5794542461090566785L;
	private long tid;
	private String messagetype;
	private String transactiontype;
	private String senderbank;
	private String receivebank;
	private String checklevel;
	private Long amountupperlimit;
	private String notes;
	private String remarks;

	public CnapsAmountLimitDO() {
	}

	public CnapsAmountLimitDO(long tid) {
		this.tid = tid;
	}

	public CnapsAmountLimitDO(long tid, String messagetype,
			String transactiontype, String senderbank, String receivebank,
			String checklevel, Long amountupperlimit, String notes,
			String remarks) {
		this.tid = tid;
		this.messagetype = messagetype;
		this.transactiontype = transactiontype;
		this.senderbank = senderbank;
		this.receivebank = receivebank;
		this.checklevel = checklevel;
		this.amountupperlimit = amountupperlimit;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MESSAGETYPE", length = 15)
	public String getMessagetype() {
		return this.messagetype;
	}

	public void setMessagetype(String messagetype) {
		this.messagetype = messagetype;
	}

	@Column(name = "TRANSACTIONTYPE", length = 6)
	public String getTransactiontype() {
		return this.transactiontype;
	}

	public void setTransactiontype(String transactiontype) {
		this.transactiontype = transactiontype;
	}

	@Column(name = "SENDERBANK", length = 14)
	public String getSenderbank() {
		return this.senderbank;
	}

	public void setSenderbank(String senderbank) {
		this.senderbank = senderbank;
	}

	@Column(name = "RECEIVEBANK", length = 14)
	public String getReceivebank() {
		return this.receivebank;
	}

	public void setReceivebank(String receivebank) {
		this.receivebank = receivebank;
	}

	@Column(name = "CHECKLEVEL", length = 2)
	public String getChecklevel() {
		return this.checklevel;
	}

	public void setChecklevel(String checklevel) {
		this.checklevel = checklevel;
	}

	@Column(name = "AMOUNTUPPERLIMIT", precision = 12, scale = 0)
	public Long getAmountupperlimit() {
		return this.amountupperlimit;
	}

	public void setAmountupperlimit(Long amountupperlimit) {
		this.amountupperlimit = amountupperlimit;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
