package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsCollectSingleLog generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_COLLECT_SINGLE_LOG")
public class CnapsCollectSingleLogDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 7214130615602821762L;
	private long tid;
	private String msgid;
	private String batchno;
	private String txid;
	private String debtorname;
	private String debtoraccountno;
	private String debtoragentcode;
	private String debtorbranchcode;
	private String creditoragentcode;
	private String creditorbranchcode;
	private String creditorname;
	private String creditoraccountno;
	private long amount;
	private String categorypurposecode;
	private String purposeproprietary;
	private String endtoendidentification;
	private String checkflag;
	private String npcprocessstatus;
	private String npcprocesscode;
	private String npcrejectinformation;
	private String npcnettingdate;
	private Byte npcnettinground;
	private String npcsettlementdate;
	private String npcreceivetime;
	private String npctransmittime;
	private String rspstatus;
	private String rsprejectcode;
	private String rspprocessparty;
	private String rsprejectinformation;
	private String rspdate;
	private String comprocessstatus;
	private String comprocesscode;
	private String compartyidentification;
	private String compartyprocesscode;
	private String comrejectinformation;
	private String comprocessdate;
	private String comnettinground;
	private String comdate;
	private String txnseqno;
	private String notes;
	private String remarks;

	public CnapsCollectSingleLogDO() {
	}

	public CnapsCollectSingleLogDO(long tid, String msgid, String batchno,
			String txid, String debtorname, String debtoraccountno,
			String debtoragentcode, String debtorbranchcode,
			String creditoragentcode, String creditorbranchcode,
			String creditorname, String creditoraccountno, long amount,
			String categorypurposecode, String purposeproprietary,
			String endtoendidentification) {
		this.tid = tid;
		this.msgid = msgid;
		this.batchno = batchno;
		this.txid = txid;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditoragentcode = creditoragentcode;
		this.creditorbranchcode = creditorbranchcode;
		this.creditorname = creditorname;
		this.creditoraccountno = creditoraccountno;
		this.amount = amount;
		this.categorypurposecode = categorypurposecode;
		this.purposeproprietary = purposeproprietary;
		this.endtoendidentification = endtoendidentification;
	}

	public CnapsCollectSingleLogDO(long tid, String msgid, String batchno,
			String txid, String debtorname, String debtoraccountno,
			String debtoragentcode, String debtorbranchcode,
			String creditoragentcode, String creditorbranchcode,
			String creditorname, String creditoraccountno, long amount,
			String categorypurposecode, String purposeproprietary,
			String endtoendidentification, String checkflag,
			String npcprocessstatus, String npcprocesscode,
			String npcrejectinformation, String npcnettingdate,
			Byte npcnettinground, String npcsettlementdate,
			String npcreceivetime, String npctransmittime, String rspstatus,
			String rsprejectcode, String rspprocessparty,
			String rsprejectinformation, String rspdate,
			String comprocessstatus, String comprocesscode,
			String compartyidentification, String compartyprocesscode,
			String comrejectinformation, String comprocessdate,
			String comnettinground, String comdate, String txnseqno,
			String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.batchno = batchno;
		this.txid = txid;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditoragentcode = creditoragentcode;
		this.creditorbranchcode = creditorbranchcode;
		this.creditorname = creditorname;
		this.creditoraccountno = creditoraccountno;
		this.amount = amount;
		this.categorypurposecode = categorypurposecode;
		this.purposeproprietary = purposeproprietary;
		this.endtoendidentification = endtoendidentification;
		this.checkflag = checkflag;
		this.npcprocessstatus = npcprocessstatus;
		this.npcprocesscode = npcprocesscode;
		this.npcrejectinformation = npcrejectinformation;
		this.npcnettingdate = npcnettingdate;
		this.npcnettinground = npcnettinground;
		this.npcsettlementdate = npcsettlementdate;
		this.npcreceivetime = npcreceivetime;
		this.npctransmittime = npctransmittime;
		this.rspstatus = rspstatus;
		this.rsprejectcode = rsprejectcode;
		this.rspprocessparty = rspprocessparty;
		this.rsprejectinformation = rsprejectinformation;
		this.rspdate = rspdate;
		this.comprocessstatus = comprocessstatus;
		this.comprocesscode = comprocesscode;
		this.compartyidentification = compartyidentification;
		this.compartyprocesscode = compartyprocesscode;
		this.comrejectinformation = comrejectinformation;
		this.comprocessdate = comprocessdate;
		this.comnettinground = comnettinground;
		this.comdate = comdate;
		this.txnseqno = txnseqno;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", nullable = false, length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "BATCHNO", nullable = false, length = 8)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "TXID", nullable = false, length = 16)
	public String getTxid() {
		return this.txid;
	}

	public void setTxid(String txid) {
		this.txid = txid;
	}

	@Column(name = "DEBTORNAME", nullable = false, length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORACCOUNTNO", nullable = false, length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "DEBTORAGENTCODE", nullable = false, length = 14)
	public String getDebtoragentcode() {
		return this.debtoragentcode;
	}

	public void setDebtoragentcode(String debtoragentcode) {
		this.debtoragentcode = debtoragentcode;
	}

	@Column(name = "DEBTORBRANCHCODE", nullable = false, length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "CREDITORAGENTCODE", nullable = false, length = 14)
	public String getCreditoragentcode() {
		return this.creditoragentcode;
	}

	public void setCreditoragentcode(String creditoragentcode) {
		this.creditoragentcode = creditoragentcode;
	}

	@Column(name = "CREDITORBRANCHCODE", nullable = false, length = 14)
	public String getCreditorbranchcode() {
		return this.creditorbranchcode;
	}

	public void setCreditorbranchcode(String creditorbranchcode) {
		this.creditorbranchcode = creditorbranchcode;
	}

	@Column(name = "CREDITORNAME", nullable = false, length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "CREDITORACCOUNTNO", nullable = false, length = 32)
	public String getCreditoraccountno() {
		return this.creditoraccountno;
	}

	public void setCreditoraccountno(String creditoraccountno) {
		this.creditoraccountno = creditoraccountno;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 12, scale = 0)
	public long getAmount() {
		return this.amount;
	}

	public void setAmount(long amount) {
		this.amount = amount;
	}

	@Column(name = "CATEGORYPURPOSECODE", nullable = false, length = 4)
	public String getCategorypurposecode() {
		return this.categorypurposecode;
	}

	public void setCategorypurposecode(String categorypurposecode) {
		this.categorypurposecode = categorypurposecode;
	}

	@Column(name = "PURPOSEPROPRIETARY", nullable = false, length = 5)
	public String getPurposeproprietary() {
		return this.purposeproprietary;
	}

	public void setPurposeproprietary(String purposeproprietary) {
		this.purposeproprietary = purposeproprietary;
	}

	@Column(name = "ENDTOENDIDENTIFICATION", nullable = false, length = 60)
	public String getEndtoendidentification() {
		return this.endtoendidentification;
	}

	public void setEndtoendidentification(String endtoendidentification) {
		this.endtoendidentification = endtoendidentification;
	}

	@Column(name = "CHECKFLAG", length = 4)
	public String getCheckflag() {
		return this.checkflag;
	}

	public void setCheckflag(String checkflag) {
		this.checkflag = checkflag;
	}

	@Column(name = "NPCPROCESSSTATUS", length = 4)
	public String getNpcprocessstatus() {
		return this.npcprocessstatus;
	}

	public void setNpcprocessstatus(String npcprocessstatus) {
		this.npcprocessstatus = npcprocessstatus;
	}

	@Column(name = "NPCPROCESSCODE", length = 8)
	public String getNpcprocesscode() {
		return this.npcprocesscode;
	}

	public void setNpcprocesscode(String npcprocesscode) {
		this.npcprocesscode = npcprocesscode;
	}

	@Column(name = "NPCREJECTINFORMATION", length = 210)
	public String getNpcrejectinformation() {
		return this.npcrejectinformation;
	}

	public void setNpcrejectinformation(String npcrejectinformation) {
		this.npcrejectinformation = npcrejectinformation;
	}

	@Column(name = "NPCNETTINGDATE", length = 14)
	public String getNpcnettingdate() {
		return this.npcnettingdate;
	}

	public void setNpcnettingdate(String npcnettingdate) {
		this.npcnettingdate = npcnettingdate;
	}

	@Column(name = "NPCNETTINGROUND", precision = 2, scale = 0)
	public Byte getNpcnettinground() {
		return this.npcnettinground;
	}

	public void setNpcnettinground(Byte npcnettinground) {
		this.npcnettinground = npcnettinground;
	}

	@Column(name = "NPCSETTLEMENTDATE", length = 14)
	public String getNpcsettlementdate() {
		return this.npcsettlementdate;
	}

	public void setNpcsettlementdate(String npcsettlementdate) {
		this.npcsettlementdate = npcsettlementdate;
	}

	@Column(name = "NPCRECEIVETIME", length = 14)
	public String getNpcreceivetime() {
		return this.npcreceivetime;
	}

	public void setNpcreceivetime(String npcreceivetime) {
		this.npcreceivetime = npcreceivetime;
	}

	@Column(name = "NPCTRANSMITTIME", length = 14)
	public String getNpctransmittime() {
		return this.npctransmittime;
	}

	public void setNpctransmittime(String npctransmittime) {
		this.npctransmittime = npctransmittime;
	}

	@Column(name = "RSPSTATUS", length = 4)
	public String getRspstatus() {
		return this.rspstatus;
	}

	public void setRspstatus(String rspstatus) {
		this.rspstatus = rspstatus;
	}

	@Column(name = "RSPREJECTCODE", length = 4)
	public String getRsprejectcode() {
		return this.rsprejectcode;
	}

	public void setRsprejectcode(String rsprejectcode) {
		this.rsprejectcode = rsprejectcode;
	}

	@Column(name = "RSPPROCESSPARTY", length = 14)
	public String getRspprocessparty() {
		return this.rspprocessparty;
	}

	public void setRspprocessparty(String rspprocessparty) {
		this.rspprocessparty = rspprocessparty;
	}

	@Column(name = "RSPREJECTINFORMATION", length = 210)
	public String getRsprejectinformation() {
		return this.rsprejectinformation;
	}

	public void setRsprejectinformation(String rsprejectinformation) {
		this.rsprejectinformation = rsprejectinformation;
	}

	@Column(name = "RSPDATE", length = 14)
	public String getRspdate() {
		return this.rspdate;
	}

	public void setRspdate(String rspdate) {
		this.rspdate = rspdate;
	}

	@Column(name = "COMPROCESSSTATUS", length = 4)
	public String getComprocessstatus() {
		return this.comprocessstatus;
	}

	public void setComprocessstatus(String comprocessstatus) {
		this.comprocessstatus = comprocessstatus;
	}

	@Column(name = "COMPROCESSCODE", length = 8)
	public String getComprocesscode() {
		return this.comprocesscode;
	}

	public void setComprocesscode(String comprocesscode) {
		this.comprocesscode = comprocesscode;
	}

	@Column(name = "COMPARTYIDENTIFICATION", length = 14)
	public String getCompartyidentification() {
		return this.compartyidentification;
	}

	public void setCompartyidentification(String compartyidentification) {
		this.compartyidentification = compartyidentification;
	}

	@Column(name = "COMPARTYPROCESSCODE", length = 4)
	public String getCompartyprocesscode() {
		return this.compartyprocesscode;
	}

	public void setCompartyprocesscode(String compartyprocesscode) {
		this.compartyprocesscode = compartyprocesscode;
	}

	@Column(name = "COMREJECTINFORMATION", length = 210)
	public String getComrejectinformation() {
		return this.comrejectinformation;
	}

	public void setComrejectinformation(String comrejectinformation) {
		this.comrejectinformation = comrejectinformation;
	}

	@Column(name = "COMPROCESSDATE", length = 14)
	public String getComprocessdate() {
		return this.comprocessdate;
	}

	public void setComprocessdate(String comprocessdate) {
		this.comprocessdate = comprocessdate;
	}

	@Column(name = "COMNETTINGROUND", length = 2)
	public String getComnettinground() {
		return this.comnettinground;
	}

	public void setComnettinground(String comnettinground) {
		this.comnettinground = comnettinground;
	}

	@Column(name = "COMDATE", length = 14)
	public String getComdate() {
		return this.comdate;
	}

	public void setComdate(String comdate) {
		this.comdate = comdate;
	}

	@Column(name = "TXNSEQNO", length = 16)
	public String getTxnseqno() {
		return this.txnseqno;
	}

	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
