package com.zcbspay.platform.cnaps.message.pojo;
// default package
// Generated 2017-3-3 11:03:08 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsTotalBill generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_TOTAL_BILL")
public class CnapsTotalBillDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 3523573274775466966L;
	private long tid;
	private String msgid;
	private String checkdate;
	private String cpiTransactionnettingdate;
	private Byte cpiTransactionnettinground;
	private String cpiMessagetype;
	private Integer cpiTotalcount;
	private Integer cpiSendtotalcount;
	private Long cpiSendtotalamount;
	private Integer cpiReceivetotalcount;
	private Long cpiReceivetotalamount;
	private String cpiProcessstatus;
	private String cmMessagetype;
	private Integer cmTotalcount;
	private Integer cmSendtotalcount;
	private Long cmReceivetotalcount;
	private String cmReceivedate;
	private String downloadstatus;
	private String notes;
	private String remarks;

	public CnapsTotalBillDO() {
	}

	public CnapsTotalBillDO(long tid) {
		this.tid = tid;
	}

	public CnapsTotalBillDO(long tid, String msgid, String checkdate,
			String cpiTransactionnettingdate, Byte cpiTransactionnettinground,
			String cpiMessagetype, Integer cpiTotalcount,
			Integer cpiSendtotalcount, Long cpiSendtotalamount,
			Integer cpiReceivetotalcount, Long cpiReceivetotalamount,
			String cpiProcessstatus, String cmMessagetype,
			Integer cmTotalcount, Integer cmSendtotalcount,
			Long cmReceivetotalcount, String cmReceivedate,
			String downloadstatus, String notes, String remarks) {
		this.tid = tid;
		this.msgid = msgid;
		this.checkdate = checkdate;
		this.cpiTransactionnettingdate = cpiTransactionnettingdate;
		this.cpiTransactionnettinground = cpiTransactionnettinground;
		this.cpiMessagetype = cpiMessagetype;
		this.cpiTotalcount = cpiTotalcount;
		this.cpiSendtotalcount = cpiSendtotalcount;
		this.cpiSendtotalamount = cpiSendtotalamount;
		this.cpiReceivetotalcount = cpiReceivetotalcount;
		this.cpiReceivetotalamount = cpiReceivetotalamount;
		this.cpiProcessstatus = cpiProcessstatus;
		this.cmMessagetype = cmMessagetype;
		this.cmTotalcount = cmTotalcount;
		this.cmSendtotalcount = cmSendtotalcount;
		this.cmReceivetotalcount = cmReceivetotalcount;
		this.cmReceivedate = cmReceivedate;
		this.downloadstatus = downloadstatus;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "MSGID", length = 35)
	public String getMsgid() {
		return this.msgid;
	}

	public void setMsgid(String msgid) {
		this.msgid = msgid;
	}

	@Column(name = "CHECKDATE", length = 14)
	public String getCheckdate() {
		return this.checkdate;
	}

	public void setCheckdate(String checkdate) {
		this.checkdate = checkdate;
	}

	@Column(name = "CPI_TRANSACTIONNETTINGDATE", length = 14)
	public String getCpiTransactionnettingdate() {
		return this.cpiTransactionnettingdate;
	}

	public void setCpiTransactionnettingdate(String cpiTransactionnettingdate) {
		this.cpiTransactionnettingdate = cpiTransactionnettingdate;
	}

	@Column(name = "CPI_TRANSACTIONNETTINGROUND", precision = 2, scale = 0)
	public Byte getCpiTransactionnettinground() {
		return this.cpiTransactionnettinground;
	}

	public void setCpiTransactionnettinground(Byte cpiTransactionnettinground) {
		this.cpiTransactionnettinground = cpiTransactionnettinground;
	}

	@Column(name = "CPI_MESSAGETYPE", length = 35)
	public String getCpiMessagetype() {
		return this.cpiMessagetype;
	}

	public void setCpiMessagetype(String cpiMessagetype) {
		this.cpiMessagetype = cpiMessagetype;
	}

	@Column(name = "CPI_TOTALCOUNT", precision = 8, scale = 0)
	public Integer getCpiTotalcount() {
		return this.cpiTotalcount;
	}

	public void setCpiTotalcount(Integer cpiTotalcount) {
		this.cpiTotalcount = cpiTotalcount;
	}

	@Column(name = "CPI_SENDTOTALCOUNT", precision = 8, scale = 0)
	public Integer getCpiSendtotalcount() {
		return this.cpiSendtotalcount;
	}

	public void setCpiSendtotalcount(Integer cpiSendtotalcount) {
		this.cpiSendtotalcount = cpiSendtotalcount;
	}

	@Column(name = "CPI_SENDTOTALAMOUNT", precision = 12, scale = 0)
	public Long getCpiSendtotalamount() {
		return this.cpiSendtotalamount;
	}

	public void setCpiSendtotalamount(Long cpiSendtotalamount) {
		this.cpiSendtotalamount = cpiSendtotalamount;
	}

	@Column(name = "CPI_RECEIVETOTALCOUNT", precision = 8, scale = 0)
	public Integer getCpiReceivetotalcount() {
		return this.cpiReceivetotalcount;
	}

	public void setCpiReceivetotalcount(Integer cpiReceivetotalcount) {
		this.cpiReceivetotalcount = cpiReceivetotalcount;
	}

	@Column(name = "CPI_RECEIVETOTALAMOUNT", precision = 12, scale = 0)
	public Long getCpiReceivetotalamount() {
		return this.cpiReceivetotalamount;
	}

	public void setCpiReceivetotalamount(Long cpiReceivetotalamount) {
		this.cpiReceivetotalamount = cpiReceivetotalamount;
	}

	@Column(name = "CPI_PROCESSSTATUS", length = 4)
	public String getCpiProcessstatus() {
		return this.cpiProcessstatus;
	}

	public void setCpiProcessstatus(String cpiProcessstatus) {
		this.cpiProcessstatus = cpiProcessstatus;
	}

	@Column(name = "CM_MESSAGETYPE", length = 35)
	public String getCmMessagetype() {
		return this.cmMessagetype;
	}

	public void setCmMessagetype(String cmMessagetype) {
		this.cmMessagetype = cmMessagetype;
	}

	@Column(name = "CM_TOTALCOUNT", precision = 8, scale = 0)
	public Integer getCmTotalcount() {
		return this.cmTotalcount;
	}

	public void setCmTotalcount(Integer cmTotalcount) {
		this.cmTotalcount = cmTotalcount;
	}

	@Column(name = "CM_SENDTOTALCOUNT", precision = 8, scale = 0)
	public Integer getCmSendtotalcount() {
		return this.cmSendtotalcount;
	}

	public void setCmSendtotalcount(Integer cmSendtotalcount) {
		this.cmSendtotalcount = cmSendtotalcount;
	}

	@Column(name = "CM_RECEIVETOTALCOUNT", precision = 12, scale = 0)
	public Long getCmReceivetotalcount() {
		return this.cmReceivetotalcount;
	}

	public void setCmReceivetotalcount(Long cmReceivetotalcount) {
		this.cmReceivetotalcount = cmReceivetotalcount;
	}

	@Column(name = "CM_RECEIVEDATE", length = 14)
	public String getCmReceivedate() {
		return this.cmReceivedate;
	}

	public void setCmReceivedate(String cmReceivedate) {
		this.cmReceivedate = cmReceivedate;
	}

	@Column(name = "DOWNLOADSTATUS", length = 2)
	public String getDownloadstatus() {
		return this.downloadstatus;
	}

	public void setDownloadstatus(String downloadstatus) {
		this.downloadstatus = downloadstatus;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
