//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:54:13 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.CommunicationConfirmation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComConfV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComConfV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConfInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.990.001.02}ConfInfV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComConfV01", propOrder = {
    "confInf"
})
public class ComConfV01 {

    @XmlElement(name = "ConfInf", required = true)
    protected ConfInfV01 confInf;

    /**
     * Gets the value of the confInf property.
     * 
     * @return
     *     possible object is
     *     {@link ConfInfV01 }
     *     
     */
    public ConfInfV01 getConfInf() {
        return confInf;
    }

    /**
     * Sets the value of the confInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfInfV01 }
     *     
     */
    public void setConfInf(ConfInfV01 value) {
        this.confInf = value;
    }

}
