//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:07:54 AM CST 
//


package com.zcbspay.platform.cnaps.beps.bean.TotalCheckInformationRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TtlChckInfReq" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.720.001.01}TotalCheckInformationRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "ttlChckInfReq"
})
public class Document {

    @XmlElement(name = "TtlChckInfReq", required = true)
    protected TotalCheckInformationRequest ttlChckInfReq;

    /**
     * Gets the value of the ttlChckInfReq property.
     * 
     * @return
     *     possible object is
     *     {@link TotalCheckInformationRequest }
     *     
     */
    public TotalCheckInformationRequest getTtlChckInfReq() {
        return ttlChckInfReq;
    }

    /**
     * Sets the value of the ttlChckInfReq property.
     * 
     * @param value
     *     allowed object is
     *     {@link TotalCheckInformationRequest }
     *     
     */
    public void setTtlChckInfReq(TotalCheckInformationRequest value) {
        this.ttlChckInfReq = value;
    }

}
