//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CashClearingSystem1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CashClearingSystem1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ABE"/>
 *     &lt;enumeration value="ART"/>
 *     &lt;enumeration value="AVP"/>
 *     &lt;enumeration value="AZM"/>
 *     &lt;enumeration value="BAP"/>
 *     &lt;enumeration value="BEL"/>
 *     &lt;enumeration value="BOF"/>
 *     &lt;enumeration value="BRL"/>
 *     &lt;enumeration value="CAD"/>
 *     &lt;enumeration value="CAM"/>
 *     &lt;enumeration value="CBJ"/>
 *     &lt;enumeration value="CHP"/>
 *     &lt;enumeration value="DKC"/>
 *     &lt;enumeration value="RTP"/>
 *     &lt;enumeration value="EBA"/>
 *     &lt;enumeration value="ELS"/>
 *     &lt;enumeration value="ERP"/>
 *     &lt;enumeration value="XCT"/>
 *     &lt;enumeration value="HRK"/>
 *     &lt;enumeration value="HRM"/>
 *     &lt;enumeration value="HUF"/>
 *     &lt;enumeration value="LGS"/>
 *     &lt;enumeration value="LVL"/>
 *     &lt;enumeration value="MOS"/>
 *     &lt;enumeration value="MUP"/>
 *     &lt;enumeration value="NOC"/>
 *     &lt;enumeration value="PCH"/>
 *     &lt;enumeration value="PDS"/>
 *     &lt;enumeration value="PEG"/>
 *     &lt;enumeration value="PNS"/>
 *     &lt;enumeration value="PVE"/>
 *     &lt;enumeration value="SEC"/>
 *     &lt;enumeration value="SIT"/>
 *     &lt;enumeration value="SLB"/>
 *     &lt;enumeration value="SPG"/>
 *     &lt;enumeration value="SSK"/>
 *     &lt;enumeration value="TBF"/>
 *     &lt;enumeration value="TGT"/>
 *     &lt;enumeration value="TOP"/>
 *     &lt;enumeration value="FDW"/>
 *     &lt;enumeration value="BOJ"/>
 *     &lt;enumeration value="FEY"/>
 *     &lt;enumeration value="ZEN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CashClearingSystem1Code")
@XmlEnum
public enum CashClearingSystem1Code {

    ABE,
    ART,
    AVP,
    AZM,
    BAP,
    BEL,
    BOF,
    BRL,
    CAD,
    CAM,
    CBJ,
    CHP,
    DKC,
    RTP,
    EBA,
    ELS,
    ERP,
    XCT,
    HRK,
    HRM,
    HUF,
    LGS,
    LVL,
    MOS,
    MUP,
    NOC,
    PCH,
    PDS,
    PEG,
    PNS,
    PVE,
    SEC,
    SIT,
    SLB,
    SPG,
    SSK,
    TBF,
    TGT,
    TOP,
    FDW,
    BOJ,
    FEY,
    ZEN;

    public String value() {
        return name();
    }

    public static CashClearingSystem1Code fromValue(String v) {
        return valueOf(v);
    }

}
