//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:swift:xsd:camt.005.001.04", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;
