//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentType3Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentType3Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CBS"/>
 *     &lt;enumeration value="BCK"/>
 *     &lt;enumeration value="BAL"/>
 *     &lt;enumeration value="CLS"/>
 *     &lt;enumeration value="CTR"/>
 *     &lt;enumeration value="CBH"/>
 *     &lt;enumeration value="CBP"/>
 *     &lt;enumeration value="DPG"/>
 *     &lt;enumeration value="DPN"/>
 *     &lt;enumeration value="EXP"/>
 *     &lt;enumeration value="TCH"/>
 *     &lt;enumeration value="LMT"/>
 *     &lt;enumeration value="LIQ"/>
 *     &lt;enumeration value="DPP"/>
 *     &lt;enumeration value="DPH"/>
 *     &lt;enumeration value="DPS"/>
 *     &lt;enumeration value="STF"/>
 *     &lt;enumeration value="TRP"/>
 *     &lt;enumeration value="TCS"/>
 *     &lt;enumeration value="LOA"/>
 *     &lt;enumeration value="LOR"/>
 *     &lt;enumeration value="TCP"/>
 *     &lt;enumeration value="OND"/>
 *     &lt;enumeration value="MGL"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentType3Code")
@XmlEnum
public enum PaymentType3Code {

    CBS,
    BCK,
    BAL,
    CLS,
    CTR,
    CBH,
    CBP,
    DPG,
    DPN,
    EXP,
    TCH,
    LMT,
    LIQ,
    DPP,
    DPH,
    DPS,
    STF,
    TRP,
    TCS,
    LOA,
    LOR,
    TCP,
    OND,
    MGL;

    public String value() {
        return name();
    }

    public static PaymentType3Code fromValue(String v) {
        return valueOf(v);
    }

}
