//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentStatusCodeSearch2Choice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PaymentStatusCodeSearch2Choice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="PdgSts" type="{urn:swift:xsd:camt.005.001.04}PendingStatus4Code"/>
 *           &lt;element name="FnlSts" type="{urn:swift:xsd:camt.005.001.04}FinalStatusCode"/>
 *           &lt;element name="PdgAndFnlSts" type="{urn:swift:xsd:camt.005.001.04}CashPaymentStatus2Code"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PaymentStatusCodeSearch2Choice", propOrder = {
    "pdgSts",
    "fnlSts",
    "pdgAndFnlSts"
})
public class PaymentStatusCodeSearch2Choice {

    @XmlElement(name = "PdgSts")
    protected PendingStatus4Code pdgSts;
    @XmlElement(name = "FnlSts")
    protected FinalStatusCode fnlSts;
    @XmlElement(name = "PdgAndFnlSts")
    protected CashPaymentStatus2Code pdgAndFnlSts;

    /**
     * Gets the value of the pdgSts property.
     * 
     * @return
     *     possible object is
     *     {@link PendingStatus4Code }
     *     
     */
    public PendingStatus4Code getPdgSts() {
        return pdgSts;
    }

    /**
     * Sets the value of the pdgSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link PendingStatus4Code }
     *     
     */
    public void setPdgSts(PendingStatus4Code value) {
        this.pdgSts = value;
    }

    /**
     * Gets the value of the fnlSts property.
     * 
     * @return
     *     possible object is
     *     {@link FinalStatusCode }
     *     
     */
    public FinalStatusCode getFnlSts() {
        return fnlSts;
    }

    /**
     * Sets the value of the fnlSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinalStatusCode }
     *     
     */
    public void setFnlSts(FinalStatusCode value) {
        this.fnlSts = value;
    }

    /**
     * Gets the value of the pdgAndFnlSts property.
     * 
     * @return
     *     possible object is
     *     {@link CashPaymentStatus2Code }
     *     
     */
    public CashPaymentStatus2Code getPdgAndFnlSts() {
        return pdgAndFnlSts;
    }

    /**
     * Sets the value of the pdgAndFnlSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CashPaymentStatus2Code }
     *     
     */
    public void setPdgAndFnlSts(CashPaymentStatus2Code value) {
        this.pdgAndFnlSts = value;
    }

}
