//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PaymentInstrument1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PaymentInstrument1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BDT"/>
 *     &lt;enumeration value="BCT"/>
 *     &lt;enumeration value="CDT"/>
 *     &lt;enumeration value="CCT"/>
 *     &lt;enumeration value="CHK"/>
 *     &lt;enumeration value="BKT"/>
 *     &lt;enumeration value="DCP"/>
 *     &lt;enumeration value="CCP"/>
 *     &lt;enumeration value="RTI"/>
 *     &lt;enumeration value="CAN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PaymentInstrument1Code")
@XmlEnum
public enum PaymentInstrument1Code {

    BDT,
    BCT,
    CDT,
    CCT,
    CHK,
    BKT,
    DCP,
    CCP,
    RTI,
    CAN;

    public String value() {
        return name();
    }

    public static PaymentInstrument1Code fromValue(String v) {
        return valueOf(v);
    }

}
