//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PendingStatus4Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PendingStatus4Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ACPD"/>
 *     &lt;enumeration value="VALD"/>
 *     &lt;enumeration value="MATD"/>
 *     &lt;enumeration value="AUTD"/>
 *     &lt;enumeration value="INVD"/>
 *     &lt;enumeration value="UMAC"/>
 *     &lt;enumeration value="STLE"/>
 *     &lt;enumeration value="STLM"/>
 *     &lt;enumeration value="SSPD"/>
 *     &lt;enumeration value="PCAN"/>
 *     &lt;enumeration value="PSTL"/>
 *     &lt;enumeration value="PFST"/>
 *     &lt;enumeration value="SMLR"/>
 *     &lt;enumeration value="RMLR"/>
 *     &lt;enumeration value="SRBL"/>
 *     &lt;enumeration value="AVLB"/>
 *     &lt;enumeration value="SRML"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PendingStatus4Code")
@XmlEnum
public enum PendingStatus4Code {

    ACPD,
    VALD,
    MATD,
    AUTD,
    INVD,
    UMAC,
    STLE,
    STLM,
    SSPD,
    PCAN,
    PSTL,
    PFST,
    SMLR,
    RMLR,
    SRBL,
    AVLB,
    SRML;

    public String value() {
        return name();
    }

    public static PendingStatus4Code fromValue(String v) {
        return valueOf(v);
    }

}
