//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RequestType1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RequestType1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RT01"/>
 *     &lt;enumeration value="RT02"/>
 *     &lt;enumeration value="RT03"/>
 *     &lt;enumeration value="RT04"/>
 *     &lt;enumeration value="RT05"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RequestType1Code")
@XmlEnum
public enum RequestType1Code {

    @XmlEnumValue("RT01")
    RT_01("RT01"),
    @XmlEnumValue("RT02")
    RT_02("RT02"),
    @XmlEnumValue("RT03")
    RT_03("RT03"),
    @XmlEnumValue("RT04")
    RT_04("RT04"),
    @XmlEnumValue("RT05")
    RT_05("RT05");
    private final String value;

    RequestType1Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RequestType1Code fromValue(String v) {
        for (RequestType1Code c: RequestType1Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
