//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:24 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionRequest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionSearchCriteria3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionSearchCriteria3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PmtTo" type="{urn:swift:xsd:camt.005.001.04}SystemSearch2" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PmtFr" type="{urn:swift:xsd:camt.005.001.04}SystemSearch2" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PmtSch" type="{urn:swift:xsd:camt.005.001.04}PaymentSearch3" minOccurs="0"/>
 *         &lt;element name="AcctNtrySch" type="{urn:swift:xsd:camt.005.001.04}AccountCashEntrySearch2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionSearchCriteria3", propOrder = {
    "pmtTo",
    "pmtFr",
    "pmtSch",
    "acctNtrySch"
})
public class TransactionSearchCriteria3 {

    @XmlElement(name = "PmtTo")
    protected List<SystemSearch2> pmtTo;
    @XmlElement(name = "PmtFr")
    protected List<SystemSearch2> pmtFr;
    @XmlElement(name = "PmtSch")
    protected PaymentSearch3 pmtSch;
    @XmlElement(name = "AcctNtrySch")
    protected AccountCashEntrySearch2 acctNtrySch;

    /**
     * Gets the value of the pmtTo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pmtTo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPmtTo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemSearch2 }
     * 
     * 
     */
    public List<SystemSearch2> getPmtTo() {
        if (pmtTo == null) {
            pmtTo = new ArrayList<SystemSearch2>();
        }
        return this.pmtTo;
    }

    /**
     * Gets the value of the pmtFr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pmtFr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPmtFr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemSearch2 }
     * 
     * 
     */
    public List<SystemSearch2> getPmtFr() {
        if (pmtFr == null) {
            pmtFr = new ArrayList<SystemSearch2>();
        }
        return this.pmtFr;
    }

    /**
     * Gets the value of the pmtSch property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentSearch3 }
     *     
     */
    public PaymentSearch3 getPmtSch() {
        return pmtSch;
    }

    /**
     * Sets the value of the pmtSch property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentSearch3 }
     *     
     */
    public void setPmtSch(PaymentSearch3 value) {
        this.pmtSch = value;
    }

    /**
     * Gets the value of the acctNtrySch property.
     * 
     * @return
     *     possible object is
     *     {@link AccountCashEntrySearch2 }
     *     
     */
    public AccountCashEntrySearch2 getAcctNtrySch() {
        return acctNtrySch;
    }

    /**
     * Sets the value of the acctNtrySch property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccountCashEntrySearch2 }
     *     
     */
    public void setAcctNtrySch(AccountCashEntrySearch2 value) {
        this.acctNtrySch = value;
    }

}
