//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:18 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BusinessQueryResponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusinessQueryTypeCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusinessQueryTypeCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="QT00"/>
 *     &lt;enumeration value="QT01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusinessQueryTypeCode1")
@XmlEnum
public enum BusinessQueryTypeCode1 {

    @XmlEnumValue("QT00")
    QT_00("QT00"),
    @XmlEnumValue("QT01")
    QT_01("QT01");
    private final String value;

    BusinessQueryTypeCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusinessQueryTypeCode1 fromValue(String v) {
        for (BusinessQueryTypeCode1 c: BusinessQueryTypeCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
