//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:29 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionResponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ErrorHandling1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ErrorHandling1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="X020"/>
 *     &lt;enumeration value="X030"/>
 *     &lt;enumeration value="X050"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ErrorHandling1Code")
@XmlEnum
public enum ErrorHandling1Code {

    @XmlEnumValue("X020")
    X_020("X020"),
    @XmlEnumValue("X030")
    X_030("X030"),
    @XmlEnumValue("X050")
    X_050("X050");
    private final String value;

    ErrorHandling1Code(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ErrorHandling1Code fromValue(String v) {
        for (ErrorHandling1Code c: ErrorHandling1Code.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
