//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:29 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionResponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PendingSettlement2Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PendingSettlement2Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AWMO"/>
 *     &lt;enumeration value="CAIS"/>
 *     &lt;enumeration value="REFU"/>
 *     &lt;enumeration value="AWSH"/>
 *     &lt;enumeration value="PHSE"/>
 *     &lt;enumeration value="TAMM"/>
 *     &lt;enumeration value="DOCY"/>
 *     &lt;enumeration value="DOCC"/>
 *     &lt;enumeration value="BLOC"/>
 *     &lt;enumeration value="CHAS"/>
 *     &lt;enumeration value="NEWI"/>
 *     &lt;enumeration value="CLAC"/>
 *     &lt;enumeration value="MUNO"/>
 *     &lt;enumeration value="GLOB"/>
 *     &lt;enumeration value="PREA"/>
 *     &lt;enumeration value="GUAD"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="NMAS"/>
 *     &lt;enumeration value="CMON"/>
 *     &lt;enumeration value="YCOL"/>
 *     &lt;enumeration value="COLL"/>
 *     &lt;enumeration value="DEPO"/>
 *     &lt;enumeration value="FLIM"/>
 *     &lt;enumeration value="NOFX"/>
 *     &lt;enumeration value="INCA"/>
 *     &lt;enumeration value="LINK"/>
 *     &lt;enumeration value="FUTU"/>
 *     &lt;enumeration value="LACK"/>
 *     &lt;enumeration value="LALO"/>
 *     &lt;enumeration value="MONY"/>
 *     &lt;enumeration value="NCON"/>
 *     &lt;enumeration value="REFS"/>
 *     &lt;enumeration value="SDUT"/>
 *     &lt;enumeration value="BATC"/>
 *     &lt;enumeration value="CYCL"/>
 *     &lt;enumeration value="SBLO"/>
 *     &lt;enumeration value="CPEC"/>
 *     &lt;enumeration value="MINO"/>
 *     &lt;enumeration value="PCAP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PendingSettlement2Code")
@XmlEnum
public enum PendingSettlement2Code {

    AWMO,
    CAIS,
    REFU,
    AWSH,
    PHSE,
    TAMM,
    DOCY,
    DOCC,
    BLOC,
    CHAS,
    NEWI,
    CLAC,
    MUNO,
    GLOB,
    PREA,
    GUAD,
    PART,
    NMAS,
    CMON,
    YCOL,
    COLL,
    DEPO,
    FLIM,
    NOFX,
    INCA,
    LINK,
    FUTU,
    LACK,
    LALO,
    MONY,
    NCON,
    REFS,
    SDUT,
    BATC,
    CYCL,
    SBLO,
    CPEC,
    MINO,
    PCAP;

    public String value() {
        return name();
    }

    public static PendingSettlement2Code fromValue(String v) {
        return valueOf(v);
    }

}
