//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:29 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.GetTransactionResponse;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PendingFailingSettlement1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PendingFailingSettlement1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AWMO"/>
 *     &lt;enumeration value="AWSH"/>
 *     &lt;enumeration value="LAAW"/>
 *     &lt;enumeration value="DOCY"/>
 *     &lt;enumeration value="CLAT"/>
 *     &lt;enumeration value="CERT"/>
 *     &lt;enumeration value="MINO"/>
 *     &lt;enumeration value="PHSE"/>
 *     &lt;enumeration value="SBLO"/>
 *     &lt;enumeration value="DKNY"/>
 *     &lt;enumeration value="STCD"/>
 *     &lt;enumeration value="BENO"/>
 *     &lt;enumeration value="LACK"/>
 *     &lt;enumeration value="LATE"/>
 *     &lt;enumeration value="CANR"/>
 *     &lt;enumeration value="MLAT"/>
 *     &lt;enumeration value="OBJT"/>
 *     &lt;enumeration value="DOCC"/>
 *     &lt;enumeration value="BLOC"/>
 *     &lt;enumeration value="CHAS"/>
 *     &lt;enumeration value="NEWI"/>
 *     &lt;enumeration value="CLAC"/>
 *     &lt;enumeration value="PART"/>
 *     &lt;enumeration value="CMON"/>
 *     &lt;enumeration value="COLL"/>
 *     &lt;enumeration value="DEPO"/>
 *     &lt;enumeration value="FLIM"/>
 *     &lt;enumeration value="NOFX"/>
 *     &lt;enumeration value="INCA"/>
 *     &lt;enumeration value="LINK"/>
 *     &lt;enumeration value="BYIY"/>
 *     &lt;enumeration value="CAIS"/>
 *     &lt;enumeration value="LALO"/>
 *     &lt;enumeration value="MONY"/>
 *     &lt;enumeration value="NCON"/>
 *     &lt;enumeration value="YCOL"/>
 *     &lt;enumeration value="REFS"/>
 *     &lt;enumeration value="SDUT"/>
 *     &lt;enumeration value="CYCL"/>
 *     &lt;enumeration value="BATC"/>
 *     &lt;enumeration value="GUAD"/>
 *     &lt;enumeration value="PREA"/>
 *     &lt;enumeration value="GLOB"/>
 *     &lt;enumeration value="CPEC"/>
 *     &lt;enumeration value="MUNO"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PendingFailingSettlement1Code")
@XmlEnum
public enum PendingFailingSettlement1Code {

    AWMO,
    AWSH,
    LAAW,
    DOCY,
    CLAT,
    CERT,
    MINO,
    PHSE,
    SBLO,
    DKNY,
    STCD,
    BENO,
    LACK,
    LATE,
    CANR,
    MLAT,
    OBJT,
    DOCC,
    BLOC,
    CHAS,
    NEWI,
    CLAC,
    PART,
    CMON,
    COLL,
    DEPO,
    FLIM,
    NOFX,
    INCA,
    LINK,
    BYIY,
    CAIS,
    LALO,
    MONY,
    NCON,
    YCOL,
    REFS,
    SDUT,
    CYCL,
    BATC,
    GUAD,
    PREA,
    GLOB,
    CPEC,
    MUNO;

    public String value() {
        return name();
    }

    public static PendingFailingSettlement1Code fromValue(String v) {
        return valueOf(v);
    }

}
