//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.06 at 04:31:35 PM CST 
//


package com.zcbspay.platform.cnaps.beps.bean.RealTimeCollectionChargesResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RealTmColltnChrgsRspn" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.385.001.01}RealTmColltnChrgsRspnV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "realTmColltnChrgsRspn"
})
public class Document {

    @XmlElement(name = "RealTmColltnChrgsRspn", required = true)
    protected RealTmColltnChrgsRspnV01 realTmColltnChrgsRspn;

    /**
     * Gets the value of the realTmColltnChrgsRspn property.
     * 
     * @return
     *     possible object is
     *     {@link RealTmColltnChrgsRspnV01 }
     *     
     */
    public RealTmColltnChrgsRspnV01 getRealTmColltnChrgsRspn() {
        return realTmColltnChrgsRspn;
    }

    /**
     * Sets the value of the realTmColltnChrgsRspn property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealTmColltnChrgsRspnV01 }
     *     
     */
    public void setRealTmColltnChrgsRspn(RealTmColltnChrgsRspnV01 value) {
        this.realTmColltnChrgsRspn = value;
    }

}
