//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:26 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.CertificateNotification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CertNtfctnInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CertNtfctnInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChgTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.903.001.02}ChangeCode1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CertNtfctnInf1", propOrder = {
    "chgTp"
})
public class CertNtfctnInf1 {

    @XmlElement(name = "ChgTp", required = true)
    protected ChangeCode1 chgTp;

    /**
     * Gets the value of the chgTp property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeCode1 }
     *     
     */
    public ChangeCode1 getChgTp() {
        return chgTp;
    }

    /**
     * Sets the value of the chgTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeCode1 }
     *     
     */
    public void setChgTp(ChangeCode1 value) {
        this.chgTp = value;
    }

}
