//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:26 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.CertificateNotification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChangeCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChangeCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CC00"/>
 *     &lt;enumeration value="CC01"/>
 *     &lt;enumeration value="CC02"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChangeCode1")
@XmlEnum
public enum ChangeCode1 {

    @XmlEnumValue("CC00")
    CC_00("CC00"),
    @XmlEnumValue("CC01")
    CC_01("CC01"),
    @XmlEnumValue("CC02")
    CC_02("CC02");
    private final String value;

    ChangeCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChangeCode1 fromValue(String v) {
        for (ChangeCode1 c: ChangeCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
