//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 10:08:02 AM CST 
//


package com.zcbspay.platform.cnaps.beps.bean.TotalCheckInformationResponse;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CheckMessageDetails1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CheckMessageDetails1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MT" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.721.001.01}Max35Text"/>
 *         &lt;element name="SndTtlCnt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.721.001.01}Max8NumericText"/>
 *         &lt;element name="RcvTtlCnt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.721.001.01}Max8NumericText"/>
 *         &lt;element name="RcvDt" type="{urn:cnaps:std:beps:2010:tech:xsd:beps.721.001.01}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CheckMessageDetails1", propOrder = {
    "mt",
    "sndTtlCnt",
    "rcvTtlCnt",
    "rcvDt"
})
public class CheckMessageDetails1 {

    @XmlElement(name = "MT", required = true)
    protected String mt;
    @XmlElement(name = "SndTtlCnt", required = true)
    protected String sndTtlCnt;
    @XmlElement(name = "RcvTtlCnt", required = true)
    protected String rcvTtlCnt;
    @XmlElement(name = "RcvDt", required = true)
    protected XMLGregorianCalendar rcvDt;

    /**
     * Gets the value of the mt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMT() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMT(String value) {
        this.mt = value;
    }

    /**
     * Gets the value of the sndTtlCnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndTtlCnt() {
        return sndTtlCnt;
    }

    /**
     * Sets the value of the sndTtlCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndTtlCnt(String value) {
        this.sndTtlCnt = value;
    }

    /**
     * Gets the value of the rcvTtlCnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvTtlCnt() {
        return rcvTtlCnt;
    }

    /**
     * Sets the value of the rcvTtlCnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvTtlCnt(String value) {
        this.rcvTtlCnt = value;
    }

    /**
     * Gets the value of the rcvDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRcvDt() {
        return rcvDt;
    }

    /**
     * Sets the value of the rcvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRcvDt(XMLGregorianCalendar value) {
        this.rcvDt = value;
    }

}
