package com.zcbspay.platform.cnaps.application.dao.pojo;
// default package
// Generated 2017-2-28 16:21:23 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TChannelCollectDeta generated by hbm2java
 */
@Entity
@Table(name = "T_CHANNEL_COLLECT_DETA")
public class ChannelCollectDetaDO implements java.io.Serializable {

	private long tid;
	private String batchno;
	private String banknode;
	private String bankcode;
	private String accountno;
	private String accountname;
	private Long amount;
	private String endtoendidentification;
	private String busicode;
	private String rspcode;
	private String rspmsg;
	private String orinorderno;
	private String txid;
	private String status;
	private String addinfo;
	private String notes;
	private String remarks;

	public ChannelCollectDetaDO() {
	}

	public ChannelCollectDetaDO(long tid) {
		this.tid = tid;
	}

	public ChannelCollectDetaDO(long tid, String batchno, String banknode,
			String bankcode, String accountno, String accountname, Long amount,
			String endtoendidentification, String busicode, String rspcode,
			String rspmsg, String orinorderno, String txid, String status,
			String addinfo, String notes, String remarks) {
		this.tid = tid;
		this.batchno = batchno;
		this.banknode = banknode;
		this.bankcode = bankcode;
		this.accountno = accountno;
		this.accountname = accountname;
		this.amount = amount;
		this.endtoendidentification = endtoendidentification;
		this.busicode = busicode;
		this.rspcode = rspcode;
		this.rspmsg = rspmsg;
		this.orinorderno = orinorderno;
		this.txid = txid;
		this.status = status;
		this.addinfo = addinfo;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "BANKNODE", length = 14)
	public String getBanknode() {
		return this.banknode;
	}

	public void setBanknode(String banknode) {
		this.banknode = banknode;
	}

	@Column(name = "BANKCODE", length = 14)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "ACCOUNTNO", length = 32)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	@Column(name = "ACCOUNTNAME", length = 64)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	@Column(name = "AMOUNT", precision = 12, scale = 0)
	public Long getAmount() {
		return this.amount;
	}

	public void setAmount(Long amount) {
		this.amount = amount;
	}

	@Column(name = "ENDTOENDIDENTIFICATION", length = 60)
	public String getEndtoendidentification() {
		return this.endtoendidentification;
	}

	public void setEndtoendidentification(String endtoendidentification) {
		this.endtoendidentification = endtoendidentification;
	}

	@Column(name = "BUSICODE", length = 8)
	public String getBusicode() {
		return this.busicode;
	}

	public void setBusicode(String busicode) {
		this.busicode = busicode;
	}

	@Column(name = "RSPCODE", length = 8)
	public String getRspcode() {
		return this.rspcode;
	}

	public void setRspcode(String rspcode) {
		this.rspcode = rspcode;
	}

	@Column(name = "RSPMSG", length = 128)
	public String getRspmsg() {
		return this.rspmsg;
	}

	public void setRspmsg(String rspmsg) {
		this.rspmsg = rspmsg;
	}

	@Column(name = "ORINORDERNO", length = 32)
	public String getOrinorderno() {
		return this.orinorderno;
	}

	public void setOrinorderno(String orinorderno) {
		this.orinorderno = orinorderno;
	}

	@Column(name = "TXID", length = 35)
	public String getTxid() {
		return this.txid;
	}

	public void setTxid(String txid) {
		this.txid = txid;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "ADDINFO", length = 512)
	public String getAddinfo() {
		return this.addinfo;
	}

	public void setAddinfo(String addinfo) {
		this.addinfo = addinfo;
	}

	@Column(name = "NOTES", length = 128)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 128)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
