package com.zcbspay.platform.cnaps.application.dao.pojo;
// default package
// Generated 2017-2-28 14:26:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TChannelCollectBatch generated by hbm2java
 */
@Entity
@Table(name = "T_CHANNEL_COLLECT_BATCH", schema = "PDTT")
public class ChannelCollectBatchDO implements java.io.Serializable {

	private long tid;
	private String batchno;
	private String mechno;
	private String banknode;
	private String bankcode;
	private String accountno;
	private String accountname;
	private Long totalcount;
	private Long totalamount;
	private Long successcount;
	private Long successamount;
	private Long failcount;
	private Long failamount;
	private String orinbatchno;
	private String status;
	private String notes;
	private String remarks;

	public ChannelCollectBatchDO() {
	}

	public ChannelCollectBatchDO(long tid) {
		this.tid = tid;
	}

	public ChannelCollectBatchDO(long tid, String batchno, String mechno,
			String banknode, String bankcode, String accountno,
			String accountname, Long totalcount, Long totalamount,
			Long successcount, Long successamount, Long failcount,
			Long failamount, String orinbatchno, String status, String notes,
			String remarks) {
		this.tid = tid;
		this.batchno = batchno;
		this.mechno = mechno;
		this.banknode = banknode;
		this.bankcode = bankcode;
		this.accountno = accountno;
		this.accountname = accountname;
		this.totalcount = totalcount;
		this.totalamount = totalamount;
		this.successcount = successcount;
		this.successamount = successamount;
		this.failcount = failcount;
		this.failamount = failamount;
		this.orinbatchno = orinbatchno;
		this.status = status;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "BATCHNO", length = 32)
	public String getBatchno() {
		return this.batchno;
	}

	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}

	@Column(name = "MECHNO", length = 15)
	public String getMechno() {
		return this.mechno;
	}

	public void setMechno(String mechno) {
		this.mechno = mechno;
	}

	@Column(name = "BANKNODE", length = 14)
	public String getBanknode() {
		return this.banknode;
	}

	public void setBanknode(String banknode) {
		this.banknode = banknode;
	}

	@Column(name = "BANKCODE", length = 14)
	public String getBankcode() {
		return this.bankcode;
	}

	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}

	@Column(name = "ACCOUNTNO", length = 32)
	public String getAccountno() {
		return this.accountno;
	}

	public void setAccountno(String accountno) {
		this.accountno = accountno;
	}

	@Column(name = "ACCOUNTNAME", length = 64)
	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	@Column(name = "TOTALCOUNT", precision = 12, scale = 0)
	public Long getTotalcount() {
		return this.totalcount;
	}

	public void setTotalcount(Long totalcount) {
		this.totalcount = totalcount;
	}

	@Column(name = "TOTALAMOUNT", precision = 12, scale = 0)
	public Long getTotalamount() {
		return this.totalamount;
	}

	public void setTotalamount(Long totalamount) {
		this.totalamount = totalamount;
	}

	@Column(name = "SUCCESSCOUNT", precision = 12, scale = 0)
	public Long getSuccesscount() {
		return this.successcount;
	}

	public void setSuccesscount(Long successcount) {
		this.successcount = successcount;
	}

	@Column(name = "SUCCESSAMOUNT", precision = 12, scale = 0)
	public Long getSuccessamount() {
		return this.successamount;
	}

	public void setSuccessamount(Long successamount) {
		this.successamount = successamount;
	}

	@Column(name = "FAILCOUNT", precision = 12, scale = 0)
	public Long getFailcount() {
		return this.failcount;
	}

	public void setFailcount(Long failcount) {
		this.failcount = failcount;
	}

	@Column(name = "FAILAMOUNT", precision = 12, scale = 0)
	public Long getFailamount() {
		return this.failamount;
	}

	public void setFailamount(Long failamount) {
		this.failamount = failamount;
	}

	@Column(name = "ORINBATCHNO", length = 32)
	public String getOrinbatchno() {
		return this.orinbatchno;
	}

	public void setOrinbatchno(String orinbatchno) {
		this.orinbatchno = orinbatchno;
	}

	@Column(name = "STATUS", length = 2)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
