package com.zcbspay.platform.cnaps.application.dao.pojo;
// default package
// Generated 2017-3-1 14:22:51 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TCnapsContract generated by hbm2java
 */
@Entity
@Table(name = "T_CNAPS_CONTRACT")
public class CnapsContractDO implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = 2606831732841916321L;
	private long tid;
	private String directparty;
	private String agreementnumber;
	private String contractagreementtype;
	private String debtorname;
	private String debtoraccountno;
	private String debtorissuercode;
	private String debtoragentcode;
	private String debtorbranchcode;
	private String creditorname;
	private String accountstatus;
	private String notes;
	private String remarks;

	public CnapsContractDO() {
	}

	public CnapsContractDO(long tid, String directparty, String agreementnumber,
			String debtorname, String debtoraccountno, String debtorissuercode,
			String debtoragentcode, String debtorbranchcode,
			String creditorname, String accountstatus) {
		this.tid = tid;
		this.directparty = directparty;
		this.agreementnumber = agreementnumber;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtorissuercode = debtorissuercode;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditorname = creditorname;
		this.accountstatus = accountstatus;
	}

	public CnapsContractDO(long tid, String directparty, String agreementnumber,
			String debtorname, String debtoraccountno, String debtorissuercode,
			String debtoragentcode, String debtorbranchcode,
			String creditorname, String accountstatus, String notes,
			String remarks) {
		this.tid = tid;
		this.directparty = directparty;
		this.agreementnumber = agreementnumber;
		this.debtorname = debtorname;
		this.debtoraccountno = debtoraccountno;
		this.debtorissuercode = debtorissuercode;
		this.debtoragentcode = debtoragentcode;
		this.debtorbranchcode = debtorbranchcode;
		this.creditorname = creditorname;
		this.accountstatus = accountstatus;
		this.notes = notes;
		this.remarks = remarks;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "DIRECTPARTY", nullable = false, length = 14)
	public String getDirectparty() {
		return this.directparty;
	}

	public void setDirectparty(String directparty) {
		this.directparty = directparty;
	}

	@Column(name = "AGREEMENTNUMBER", nullable = false, length = 60)
	public String getAgreementnumber() {
		return this.agreementnumber;
	}

	public void setAgreementnumber(String agreementnumber) {
		this.agreementnumber = agreementnumber;
	}

	@Column(name = "DEBTORNAME", nullable = false, length = 120)
	public String getDebtorname() {
		return this.debtorname;
	}

	public void setDebtorname(String debtorname) {
		this.debtorname = debtorname;
	}

	@Column(name = "DEBTORACCOUNTNO", nullable = false, length = 32)
	public String getDebtoraccountno() {
		return this.debtoraccountno;
	}

	public void setDebtoraccountno(String debtoraccountno) {
		this.debtoraccountno = debtoraccountno;
	}

	@Column(name = "DEBTORISSUERCODE", nullable = false, length = 14)
	public String getDebtorissuercode() {
		return this.debtorissuercode;
	}

	public void setDebtorissuercode(String debtorissuercode) {
		this.debtorissuercode = debtorissuercode;
	}

	@Column(name = "DEBTORAGENTCODE", nullable = false, length = 14)
	public String getDebtoragentcode() {
		return this.debtoragentcode;
	}

	public void setDebtoragentcode(String debtoragentcode) {
		this.debtoragentcode = debtoragentcode;
	}

	@Column(name = "DEBTORBRANCHCODE", nullable = false, length = 14)
	public String getDebtorbranchcode() {
		return this.debtorbranchcode;
	}

	public void setDebtorbranchcode(String debtorbranchcode) {
		this.debtorbranchcode = debtorbranchcode;
	}

	@Column(name = "CREDITORNAME", nullable = false, length = 120)
	public String getCreditorname() {
		return this.creditorname;
	}

	public void setCreditorname(String creditorname) {
		this.creditorname = creditorname;
	}

	@Column(name = "ACCOUNTSTATUS", nullable = false, length = 4)
	public String getAccountstatus() {
		return this.accountstatus;
	}

	public void setAccountstatus(String accountstatus) {
		this.accountstatus = accountstatus;
	}

	@Column(name = "NOTES", length = 256)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "REMARKS", length = 256)
	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	@Column(name = "CONTRACTAGREEMENTTYPE", length = 4)
	public String getContractagreementtype() {
		return this.contractagreementtype;
	}

	public void setContractagreementtype(String contractagreementtype) {
		this.contractagreementtype = contractagreementtype;
	}
}
