//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:54:10 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.TransactionAmountUpperLimit;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TxAmtUpperLmtInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TxAmtUpperLmtInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChngTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}ChangeCode1"/>
 *         &lt;element name="MT" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}Max15Text"/>
 *         &lt;element name="TxTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}Max6Text"/>
 *         &lt;element name="SndrBk" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}Max14Text"/>
 *         &lt;element name="RcvBk" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}Max14Text"/>
 *         &lt;element name="ChckLvl" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}Exact2NumericText"/>
 *         &lt;element name="AmtUpperLmt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.926.001.01}SummaryAmountText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TxAmtUpperLmtInf1", propOrder = {
    "chngTp",
    "mt",
    "txTp",
    "sndrBk",
    "rcvBk",
    "chckLvl",
    "amtUpperLmt"
})
public class TxAmtUpperLmtInf1 {

    @XmlElement(name = "ChngTp", required = true)
    protected ChangeCode1 chngTp;
    @XmlElement(name = "MT", required = true)
    protected String mt;
    @XmlElement(name = "TxTp", required = true)
    protected String txTp;
    @XmlElement(name = "SndrBk", required = true)
    protected String sndrBk;
    @XmlElement(name = "RcvBk", required = true)
    protected String rcvBk;
    @XmlElement(name = "ChckLvl", required = true)
    protected String chckLvl;
    @XmlElement(name = "AmtUpperLmt", required = true)
    protected String amtUpperLmt;

    /**
     * Gets the value of the chngTp property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeCode1 }
     *     
     */
    public ChangeCode1 getChngTp() {
        return chngTp;
    }

    /**
     * Sets the value of the chngTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeCode1 }
     *     
     */
    public void setChngTp(ChangeCode1 value) {
        this.chngTp = value;
    }

    /**
     * Gets the value of the mt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMT() {
        return mt;
    }

    /**
     * Sets the value of the mt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMT(String value) {
        this.mt = value;
    }

    /**
     * Gets the value of the txTp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTxTp() {
        return txTp;
    }

    /**
     * Sets the value of the txTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTxTp(String value) {
        this.txTp = value;
    }

    /**
     * Gets the value of the sndrBk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndrBk() {
        return sndrBk;
    }

    /**
     * Sets the value of the sndrBk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndrBk(String value) {
        this.sndrBk = value;
    }

    /**
     * Gets the value of the rcvBk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvBk() {
        return rcvBk;
    }

    /**
     * Sets the value of the rcvBk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvBk(String value) {
        this.rcvBk = value;
    }

    /**
     * Gets the value of the chckLvl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChckLvl() {
        return chckLvl;
    }

    /**
     * Sets the value of the chckLvl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChckLvl(String value) {
        this.chckLvl = value;
    }

    /**
     * Gets the value of the amtUpperLmt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtUpperLmt() {
        return amtUpperLmt;
    }

    /**
     * Sets the value of the amtUpperLmt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtUpperLmt(String value) {
        this.amtUpperLmt = value;
    }

}
