//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:14 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BusinessQueryRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for BllInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BllInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BllNb" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}Max32Text"/>
 *         &lt;element name="AccptDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}ISODate"/>
 *         &lt;element name="BllDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}ISODate"/>
 *         &lt;element name="DrftDueDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}ISODate"/>
 *         &lt;element name="DrwrFullNm" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}Max60Text"/>
 *         &lt;element name="CdtrFullNm" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}Max60Text"/>
 *         &lt;element name="DbtrBkFullNm" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}Max60Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BllInf1", propOrder = {
    "bllNb",
    "accptDt",
    "bllDt",
    "drftDueDt",
    "drwrFullNm",
    "cdtrFullNm",
    "dbtrBkFullNm"
})
public class BllInf1 {

    @XmlElement(name = "BllNb", required = true)
    protected String bllNb;
    @XmlElement(name = "AccptDt", required = true)
    protected XMLGregorianCalendar accptDt;
    @XmlElement(name = "BllDt", required = true)
    protected XMLGregorianCalendar bllDt;
    @XmlElement(name = "DrftDueDt", required = true)
    protected XMLGregorianCalendar drftDueDt;
    @XmlElement(name = "DrwrFullNm", required = true)
    protected String drwrFullNm;
    @XmlElement(name = "CdtrFullNm", required = true)
    protected String cdtrFullNm;
    @XmlElement(name = "DbtrBkFullNm", required = true)
    protected String dbtrBkFullNm;

    /**
     * Gets the value of the bllNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBllNb() {
        return bllNb;
    }

    /**
     * Sets the value of the bllNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBllNb(String value) {
        this.bllNb = value;
    }

    /**
     * Gets the value of the accptDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccptDt() {
        return accptDt;
    }

    /**
     * Sets the value of the accptDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccptDt(XMLGregorianCalendar value) {
        this.accptDt = value;
    }

    /**
     * Gets the value of the bllDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBllDt() {
        return bllDt;
    }

    /**
     * Sets the value of the bllDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBllDt(XMLGregorianCalendar value) {
        this.bllDt = value;
    }

    /**
     * Gets the value of the drftDueDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDrftDueDt() {
        return drftDueDt;
    }

    /**
     * Sets the value of the drftDueDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDrftDueDt(XMLGregorianCalendar value) {
        this.drftDueDt = value;
    }

    /**
     * Gets the value of the drwrFullNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrwrFullNm() {
        return drwrFullNm;
    }

    /**
     * Sets the value of the drwrFullNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrwrFullNm(String value) {
        this.drwrFullNm = value;
    }

    /**
     * Gets the value of the cdtrFullNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCdtrFullNm() {
        return cdtrFullNm;
    }

    /**
     * Sets the value of the cdtrFullNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCdtrFullNm(String value) {
        this.cdtrFullNm = value;
    }

    /**
     * Gets the value of the dbtrBkFullNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDbtrBkFullNm() {
        return dbtrBkFullNm;
    }

    /**
     * Sets the value of the dbtrBkFullNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDbtrBkFullNm(String value) {
        this.dbtrBkFullNm = value;
    }

}
