//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:14 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BusinessQueryRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BizQry" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.314.001.01}BizQryV01"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "bizQry"
})
public class Document {

    @XmlElement(name = "BizQry", required = true)
    protected BizQryV01 bizQry;

    /**
     * Gets the value of the bizQry property.
     * 
     * @return
     *     possible object is
     *     {@link BizQryV01 }
     *     
     */
    public BizQryV01 getBizQry() {
        return bizQry;
    }

    /**
     * Sets the value of the bizQry property.
     * 
     * @param value
     *     allowed object is
     *     {@link BizQryV01 }
     *     
     */
    public void setBizQry(BizQryV01 value) {
        this.bizQry = value;
    }

}
