//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:54:17 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.CheckRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SndSvcrMgmtInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SndSvcrMgmtInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SndSvcrRcvSts" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.991.001.01}Exact1NumericText"/>
 *         &lt;element name="SndNdMgmtSts" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.991.001.01}Exact1NumericText" minOccurs="0"/>
 *         &lt;element name="RcvNdMgmtSts" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.991.001.01}Exact1NumericText" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SndSvcrMgmtInf1", propOrder = {
    "sndSvcrRcvSts",
    "sndNdMgmtSts",
    "rcvNdMgmtSts"
})
public class SndSvcrMgmtInf1 {

    @XmlElement(name = "SndSvcrRcvSts", required = true)
    protected String sndSvcrRcvSts;
    @XmlElement(name = "SndNdMgmtSts")
    protected String sndNdMgmtSts;
    @XmlElement(name = "RcvNdMgmtSts")
    protected String rcvNdMgmtSts;

    /**
     * Gets the value of the sndSvcrRcvSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndSvcrRcvSts() {
        return sndSvcrRcvSts;
    }

    /**
     * Sets the value of the sndSvcrRcvSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndSvcrRcvSts(String value) {
        this.sndSvcrRcvSts = value;
    }

    /**
     * Gets the value of the sndNdMgmtSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSndNdMgmtSts() {
        return sndNdMgmtSts;
    }

    /**
     * Sets the value of the sndNdMgmtSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSndNdMgmtSts(String value) {
        this.sndNdMgmtSts = value;
    }

    /**
     * Gets the value of the rcvNdMgmtSts property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRcvNdMgmtSts() {
        return rcvNdMgmtSts;
    }

    /**
     * Sets the value of the rcvNdMgmtSts property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRcvNdMgmtSts(String value) {
        this.rcvNdMgmtSts = value;
    }

}
