//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:59 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BasisChangeNotification;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BsisChngNtfctnV01 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BsisChngNtfctnV01">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="GrpHdr" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}GroupHeader1"/>
 *         &lt;element name="NbInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}NbInf1"/>
 *         &lt;element name="RcrdNbInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}RcrdNbInf1"/>
 *         &lt;element name="BkTpChngInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}BkTpChngInf1" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CCPCChngInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}CCPCChngInf1" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CityChngInf" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}CityChngInf1" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BsisChngNtfctnV01", propOrder = {
    "grpHdr",
    "nbInf",
    "rcrdNbInf",
    "bkTpChngInf",
    "ccpcChngInf",
    "cityChngInf"
})
public class BsisChngNtfctnV01 {

    @XmlElement(name = "GrpHdr", required = true)
    protected GroupHeader1 grpHdr;
    @XmlElement(name = "NbInf", required = true)
    protected NbInf1 nbInf;
    @XmlElement(name = "RcrdNbInf", required = true)
    protected RcrdNbInf1 rcrdNbInf;
    @XmlElement(name = "BkTpChngInf")
    protected List<BkTpChngInf1> bkTpChngInf;
    @XmlElement(name = "CCPCChngInf")
    protected List<CCPCChngInf1> ccpcChngInf;
    @XmlElement(name = "CityChngInf")
    protected List<CityChngInf1> cityChngInf;

    /**
     * Gets the value of the grpHdr property.
     * 
     * @return
     *     possible object is
     *     {@link GroupHeader1 }
     *     
     */
    public GroupHeader1 getGrpHdr() {
        return grpHdr;
    }

    /**
     * Sets the value of the grpHdr property.
     * 
     * @param value
     *     allowed object is
     *     {@link GroupHeader1 }
     *     
     */
    public void setGrpHdr(GroupHeader1 value) {
        this.grpHdr = value;
    }

    /**
     * Gets the value of the nbInf property.
     * 
     * @return
     *     possible object is
     *     {@link NbInf1 }
     *     
     */
    public NbInf1 getNbInf() {
        return nbInf;
    }

    /**
     * Sets the value of the nbInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link NbInf1 }
     *     
     */
    public void setNbInf(NbInf1 value) {
        this.nbInf = value;
    }

    /**
     * Gets the value of the rcrdNbInf property.
     * 
     * @return
     *     possible object is
     *     {@link RcrdNbInf1 }
     *     
     */
    public RcrdNbInf1 getRcrdNbInf() {
        return rcrdNbInf;
    }

    /**
     * Sets the value of the rcrdNbInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RcrdNbInf1 }
     *     
     */
    public void setRcrdNbInf(RcrdNbInf1 value) {
        this.rcrdNbInf = value;
    }

    /**
     * Gets the value of the bkTpChngInf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the bkTpChngInf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBkTpChngInf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BkTpChngInf1 }
     * 
     * 
     */
    public List<BkTpChngInf1> getBkTpChngInf() {
        if (bkTpChngInf == null) {
            bkTpChngInf = new ArrayList<BkTpChngInf1>();
        }
        return this.bkTpChngInf;
    }

    /**
     * Gets the value of the ccpcChngInf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ccpcChngInf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCCPCChngInf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CCPCChngInf1 }
     * 
     * 
     */
    public List<CCPCChngInf1> getCCPCChngInf() {
        if (ccpcChngInf == null) {
            ccpcChngInf = new ArrayList<CCPCChngInf1>();
        }
        return this.ccpcChngInf;
    }

    /**
     * Gets the value of the cityChngInf property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cityChngInf property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCityChngInf().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CityChngInf1 }
     * 
     * 
     */
    public List<CityChngInf1> getCityChngInf() {
        if (cityChngInf == null) {
            cityChngInf = new ArrayList<CityChngInf1>();
        }
        return this.cityChngInf;
    }

}
