//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:59 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BasisChangeNotification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CCPCChngInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CCPCChngInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChngCtrl" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}ChngCtrl1"/>
 *         &lt;element name="NdCd" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Exact4NumericText"/>
 *         &lt;element name="NdNm" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Max35Text"/>
 *         &lt;element name="NdTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}NodeTypeCode1"/>
 *         &lt;element name="CityCd" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Max6NumericText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CCPCChngInf1", propOrder = {
    "chngCtrl",
    "ndCd",
    "ndNm",
    "ndTp",
    "cityCd"
})
public class CCPCChngInf1 {

    @XmlElement(name = "ChngCtrl", required = true)
    protected ChngCtrl1 chngCtrl;
    @XmlElement(name = "NdCd", required = true)
    protected String ndCd;
    @XmlElement(name = "NdNm", required = true)
    protected String ndNm;
    @XmlElement(name = "NdTp", required = true)
    protected NodeTypeCode1 ndTp;
    @XmlElement(name = "CityCd", required = true)
    protected String cityCd;

    /**
     * Gets the value of the chngCtrl property.
     * 
     * @return
     *     possible object is
     *     {@link ChngCtrl1 }
     *     
     */
    public ChngCtrl1 getChngCtrl() {
        return chngCtrl;
    }

    /**
     * Sets the value of the chngCtrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChngCtrl1 }
     *     
     */
    public void setChngCtrl(ChngCtrl1 value) {
        this.chngCtrl = value;
    }

    /**
     * Gets the value of the ndCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNdCd() {
        return ndCd;
    }

    /**
     * Sets the value of the ndCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNdCd(String value) {
        this.ndCd = value;
    }

    /**
     * Gets the value of the ndNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNdNm() {
        return ndNm;
    }

    /**
     * Sets the value of the ndNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNdNm(String value) {
        this.ndNm = value;
    }

    /**
     * Gets the value of the ndTp property.
     * 
     * @return
     *     possible object is
     *     {@link NodeTypeCode1 }
     *     
     */
    public NodeTypeCode1 getNdTp() {
        return ndTp;
    }

    /**
     * Sets the value of the ndTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodeTypeCode1 }
     *     
     */
    public void setNdTp(NodeTypeCode1 value) {
        this.ndTp = value;
    }

    /**
     * Gets the value of the cityCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityCd() {
        return cityCd;
    }

    /**
     * Sets the value of the cityCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityCd(String value) {
        this.cityCd = value;
    }

}
