//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:59 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BasisChangeNotification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ChngCtrl1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ChngCtrl1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ChngTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}ChangeCode1"/>
 *         &lt;element name="FctvTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}EffectiveCode1"/>
 *         &lt;element name="FctvDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}ISODate" minOccurs="0"/>
 *         &lt;element name="IfctvDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}ISODate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ChngCtrl1", propOrder = {
    "chngTp",
    "fctvTp",
    "fctvDt",
    "ifctvDt"
})
public class ChngCtrl1 {

    @XmlElement(name = "ChngTp", required = true)
    protected ChangeCode1 chngTp;
    @XmlElement(name = "FctvTp", required = true)
    protected EffectiveCode1 fctvTp;
    @XmlElement(name = "FctvDt")
    protected XMLGregorianCalendar fctvDt;
    @XmlElement(name = "IfctvDt")
    protected XMLGregorianCalendar ifctvDt;

    /**
     * Gets the value of the chngTp property.
     * 
     * @return
     *     possible object is
     *     {@link ChangeCode1 }
     *     
     */
    public ChangeCode1 getChngTp() {
        return chngTp;
    }

    /**
     * Sets the value of the chngTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangeCode1 }
     *     
     */
    public void setChngTp(ChangeCode1 value) {
        this.chngTp = value;
    }

    /**
     * Gets the value of the fctvTp property.
     * 
     * @return
     *     possible object is
     *     {@link EffectiveCode1 }
     *     
     */
    public EffectiveCode1 getFctvTp() {
        return fctvTp;
    }

    /**
     * Sets the value of the fctvTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectiveCode1 }
     *     
     */
    public void setFctvTp(EffectiveCode1 value) {
        this.fctvTp = value;
    }

    /**
     * Gets the value of the fctvDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFctvDt() {
        return fctvDt;
    }

    /**
     * Sets the value of the fctvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFctvDt(XMLGregorianCalendar value) {
        this.fctvDt = value;
    }

    /**
     * Gets the value of the ifctvDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIfctvDt() {
        return ifctvDt;
    }

    /**
     * Sets the value of the ifctvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIfctvDt(XMLGregorianCalendar value) {
        this.ifctvDt = value;
    }

}
