//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:59 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.BasisChangeNotification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RcrdNbInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RcrdNbInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="BkTpChngNb" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Max8NumericText"/>
 *         &lt;element name="CCPCChngNb" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Max8NumericText"/>
 *         &lt;element name="CityChngNb" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.917.001.01}Max8NumericText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RcrdNbInf1", propOrder = {
    "bkTpChngNb",
    "ccpcChngNb",
    "cityChngNb"
})
public class RcrdNbInf1 {

    @XmlElement(name = "BkTpChngNb", required = true)
    protected String bkTpChngNb;
    @XmlElement(name = "CCPCChngNb", required = true)
    protected String ccpcChngNb;
    @XmlElement(name = "CityChngNb", required = true)
    protected String cityChngNb;

    /**
     * Gets the value of the bkTpChngNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBkTpChngNb() {
        return bkTpChngNb;
    }

    /**
     * Sets the value of the bkTpChngNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBkTpChngNb(String value) {
        this.bkTpChngNb = value;
    }

    /**
     * Gets the value of the ccpcChngNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCPCChngNb() {
        return ccpcChngNb;
    }

    /**
     * Sets the value of the ccpcChngNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCPCChngNb(String value) {
        this.ccpcChngNb = value;
    }

    /**
     * Gets the value of the cityChngNb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityChngNb() {
        return cityChngNb;
    }

    /**
     * Sets the value of the cityChngNb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityChngNb(String value) {
        this.cityChngNb = value;
    }

}
