//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:51:38 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.FIToFIPaymentCancellationRequest;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CancellationReason4Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CancellationReason4Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CUST"/>
 *     &lt;enumeration value="DUPL"/>
 *     &lt;enumeration value="AGNT"/>
 *     &lt;enumeration value="CURR"/>
 *     &lt;enumeration value="UPAY"/>
 *     &lt;enumeration value="CUTA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CancellationReason4Code")
@XmlEnum
public enum CancellationReason4Code {

    CUST,
    DUPL,
    AGNT,
    CURR,
    UPAY,
    CUTA;

    public String value() {
        return name();
    }

    public static CancellationReason4Code fromValue(String v) {
        return valueOf(v);
    }

}
