//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:46 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.SystemStatusNotification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HolidayFlagCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HolidayFlagCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HF00"/>
 *     &lt;enumeration value="HF01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HolidayFlagCode1")
@XmlEnum
public enum HolidayFlagCode1 {

    @XmlEnumValue("HF00")
    HF_00("HF00"),
    @XmlEnumValue("HF01")
    HF_01("HF01");
    private final String value;

    HolidayFlagCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HolidayFlagCode1 fromValue(String v) {
        for (HolidayFlagCode1 c: HolidayFlagCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
