//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:55 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.Notification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NodeTypeCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NodeTypeCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="NT00"/>
 *     &lt;enumeration value="NT01"/>
 *     &lt;enumeration value="NT02"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NodeTypeCode1")
@XmlEnum
public enum NodeTypeCode1 {

    @XmlEnumValue("NT00")
    NT_00("NT00"),
    @XmlEnumValue("NT01")
    NT_01("NT01"),
    @XmlEnumValue("NT02")
    NT_02("NT02");
    private final String value;

    NodeTypeCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NodeTypeCode1 fromValue(String v) {
        for (NodeTypeCode1 c: NodeTypeCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
