//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:52:59 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.LoginRequest;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginInformation1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginInformation1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LoginOprTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.805.001.02}LoginOperationTypeCode1"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginInformation1", propOrder = {
    "loginOprTp"
})
public class LoginInformation1 {

    @XmlElement(name = "LoginOprTp", required = true)
    protected LoginOperationTypeCode1 loginOprTp;

    /**
     * Gets the value of the loginOprTp property.
     * 
     * @return
     *     possible object is
     *     {@link LoginOperationTypeCode1 }
     *     
     */
    public LoginOperationTypeCode1 getLoginOprTp() {
        return loginOprTp;
    }

    /**
     * Sets the value of the loginOprTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoginOperationTypeCode1 }
     *     
     */
    public void setLoginOprTp(LoginOperationTypeCode1 value) {
        this.loginOprTp = value;
    }

}
