//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:37 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.SystemParameterNotification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CommonDataCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CommonDataCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CM00"/>
 *     &lt;enumeration value="CM01"/>
 *     &lt;enumeration value="CM02"/>
 *     &lt;enumeration value="CM03"/>
 *     &lt;enumeration value="CM04"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CommonDataCode1")
@XmlEnum
public enum CommonDataCode1 {

    @XmlEnumValue("CM00")
    CM_00("CM00"),
    @XmlEnumValue("CM01")
    CM_01("CM01"),
    @XmlEnumValue("CM02")
    CM_02("CM02"),
    @XmlEnumValue("CM03")
    CM_03("CM03"),
    @XmlEnumValue("CM04")
    CM_04("CM04");
    private final String value;

    CommonDataCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CommonDataCode1 fromValue(String v) {
        for (CommonDataCode1 c: CommonDataCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
