//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:37 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.SystemParameterNotification;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EffectiveCode1.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EffectiveCode1">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EF00"/>
 *     &lt;enumeration value="EF01"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EffectiveCode1")
@XmlEnum
public enum EffectiveCode1 {

    @XmlEnumValue("EF00")
    EF_00("EF00"),
    @XmlEnumValue("EF01")
    EF_01("EF01");
    private final String value;

    EffectiveCode1(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EffectiveCode1 fromValue(String v) {
        for (EffectiveCode1 c: EffectiveCode1 .values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
