//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.01 at 03:53:37 PM CST 
//


package com.zcbspay.platform.cnaps.ccms.bean.SystemParameterNotification;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for FctvInf1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FctvInf1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FctvTp" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.907.001.02}EffectiveCode1"/>
 *         &lt;element name="FctvDt" type="{urn:cnaps:std:ccms:2010:tech:xsd:ccms.907.001.02}ISODate"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FctvInf1", propOrder = {
    "fctvTp",
    "fctvDt"
})
public class FctvInf1 {

    @XmlElement(name = "FctvTp", required = true)
    protected EffectiveCode1 fctvTp;
    @XmlElement(name = "FctvDt", required = true)
    protected XMLGregorianCalendar fctvDt;

    /**
     * Gets the value of the fctvTp property.
     * 
     * @return
     *     possible object is
     *     {@link EffectiveCode1 }
     *     
     */
    public EffectiveCode1 getFctvTp() {
        return fctvTp;
    }

    /**
     * Sets the value of the fctvTp property.
     * 
     * @param value
     *     allowed object is
     *     {@link EffectiveCode1 }
     *     
     */
    public void setFctvTp(EffectiveCode1 value) {
        this.fctvTp = value;
    }

    /**
     * Gets the value of the fctvDt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFctvDt() {
        return fctvDt;
    }

    /**
     * Sets the value of the fctvDt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFctvDt(XMLGregorianCalendar value) {
        this.fctvDt = value;
    }

}
